import { AutolinkingTestCase } from '../types'

// TODO annotate. Would perform poorly now as many duplicate component names
const backstage: AutolinkingTestCase = {
  name: 'Backstage',
  passThreshold: 0,
  figmaComponents: [
    { name: 'Mixed', id: '158:2' },
    { name: 'Down', id: '158:1' },
    { name: 'Up', id: '158:0' },
    { name: 'Home / Tabs', id: '250:0' },
    { name: 'Side Panel / 768', id: '1157:3796' },
    { name: 'Side Panel / 520', id: '1157:3827' },
    { name: 'Low Progress', id: '140:925' },
    { name: 'Medium Progress', id: '140:917' },
    { name: 'High Progress', id: '140:909' },
    { name: 'Card - Advanced', id: '140:171' },
    { name: 'Card - Advanced', id: '140:172' },
    { name: 'Card - Advanced', id: '140:128' },
    { name: 'Tutorial 3', id: '2185:6146' },
    { name: 'Card / Toolkit', id: '2185:6143' },
    { name: 'Search Bar', id: '2185:6147' },
    { name: 'Card / Composable', id: '2186:6382' },
    { name: 'Tutorial 2', id: '2185:6145' },
    { name: 'Tutorial 1', id: '2185:6144' },
    { name: 'Card / Quick Access', id: '2186:6270' },
    { name: 'Wave / Shape 4', id: '354:74' },
    { name: 'Wave / Shape 3', id: '354:67' },
    { name: 'Wave / Shape 2', id: '354:61' },
    { name: 'Wave / Shape 1', id: '354:54' },
    { name: 'Hidden Breadcrumbs', id: '1284:455' },
    { name: 'Breadcrumbs', id: '1284:334' },
    { name: 'WaveHeader / Base', id: '354:15' },
    { name: 'WaveHeader / Home', id: '354:13' },
    { name: 'WaveHeader / Service', id: '354:11' },
    { name: 'WaveHeader / Tool', id: '354:9' },
    { name: 'WaveHeader / Library', id: '354:7' },
    { name: 'WaveHeader / App', id: '354:5' },
    { name: 'WaveHeader / Website', id: '354:3' },
    { name: 'WaveHeader / Other', id: '354:1' },
    { name: 'Nondismissable Banner', id: '1244:28' },
    { name: 'Dialog / 608', id: '1244:49' },
    { name: 'Dialog / 472', id: '1244:64' },
    { name: 'Dropdown | Checkbox', id: '525:57' },
    { name: 'Dropdown', id: '524:739' },
    { name: 'Checkbox / Off', id: '524:358' },
    { name: 'Checkbox / Off', id: '524:401' },
    { name: 'Checkbox / On', id: '524:391' },
    { name: 'Input / Dropdown', id: '524:320' },
    { name: 'Empty State', id: '659:0' },
    { name: 'Banner', id: '137:1232' },
    { name: 'Banner', id: '137:1245' },
    { name: 'Banner', id: '137:771' },
    { name: 'Banner', id: '137:772' },
    { name: 'CTAs', id: '727:8' },
    { name: 'CTAs', id: '727:7' },
    { name: 'Button / Primary', id: '727:0' },
    { name: 'Button / Primary Disabled', id: '727:1' },
    { name: 'Button / Secondary', id: '727:2' },
    { name: 'Button / Secondary Disabled', id: '727:3' },
    { name: 'Button / Text with Icon Disabled', id: '727:5' },
    { name: 'Button / Text with Icon', id: '727:6' },
    { name: 'Button / Text', id: '184:71' },
    { name: 'Button / Text Disabled', id: '727:4' },
    { name: 'Small Chip / Filled Deletable', id: '404:143' },
    { name: 'Large Chip / Filled Deletable', id: '404:156' },
    { name: 'Small Chip / Filled Deletable', id: '404:122' },
    { name: 'Large Chip / Filled Not Deletable', id: '404:111' },
    { name: '01 Details Card', id: '684:1' },
    { name: 'Card - Advanced', id: '140:251' },
    { name: 'Card - Advanced', id: '140:231' },
    { name: 'Card - Advanced', id: '140:263' },
    { name: 'Card - Advanced', id: '137:734' },
    { name: 'Card - Advanced', id: '137:733' },
    { name: 'Card - Advanced', id: '140:436' },
    { name: 'Card - Advanced', id: '140:347' },
    { name: 'Card - Advanced', id: '140:689' },
    { name: 'Card - Advanced', id: '140:617' },
    { name: 'Card - Advanced', id: '140:537' },
    { name: 'Card Base', id: '140:855' },
    { name: 'Card', id: '140:793' },
    { name: 'Card', id: '140:767' },
    { name: 'WaveHeader / Tool', id: '388:995' },
    { name: 'WaveHeader / Tool', id: '388:258' },
    { name: 'Display 1', id: '727:9' },
    { name: 'Display 2', id: '727:11' },
    { name: 'Heading 1', id: '727:12' },
    { name: 'Heading 2 | Bold', id: '727:13' },
    { name: 'Heading 2', id: '730:53' },
    { name: 'Heading 3 | Bold', id: '727:14' },
    { name: 'Heading 3', id: '730:52' },
    { name: 'Body 1 | Bold', id: '727:15' },
    { name: 'Body 1', id: '730:51' },
    { name: 'Body 2', id: '730:50' },
    { name: 'Body 2 | Bold', id: '727:16' },
    { name: 'CTA', id: '727:17' },
    { name: 'CTA', id: '730:49' },
    { name: 'CTA | Uppercase', id: '727:19' },
    { name: 'CTA', id: '730:48' },
    { name: 'CTA | Uppercase', id: '727:20' },
    { name: 'CTA', id: '727:18' },
    { name: 'Breadcrumb | Underline', id: '727:23' },
    { name: 'Breadcrumb | Italic', id: '730:46' },
    { name: 'Caption', id: '727:21' },
    { name: 'Caption | Bold', id: '727:22' },
    { name: 'Caption', id: '730:47' },
  ],
  componentPaths: [
    '/Users/foo/backstage/packages/core-components/src/layout/TabbedCard/TabbedCard.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/TabbedCard/TabbedCard.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/TabbedCard/TabbedCard.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/SignInPage/styles.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/SignInPage/providers.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/SignInPage/guestProvider.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/SignInPage/customProvider.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/SignInPage/commonProvider.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/SignInPage/SignInPage.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarSubmenuItem.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarSubmenu.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarPinStateContext.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarPinStateContext.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarOpenStateContext.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarOpenStateContext.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarGroup.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/SidebarGroup.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/Sidebar.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/Page.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/MobileSidebar.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/MobileSidebar.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/Items.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/Items.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/Intro.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/Bar.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/Bar.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/icons/DoubleArrowRight.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Sidebar/icons/DoubleArrowLeft.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ProxiedSignInPage/ProxiedSignInPage.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Page/PageWithHeader.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Page/Page.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Page/Page.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ItemCard/ItemCardHeader.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ItemCard/ItemCardHeader.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ItemCard/ItemCardGrid.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ItemCard/ItemCardGrid.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ItemCard/ItemCard.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ItemCard/ItemCard.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ItemCard/ItemCard.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/InfoCard/InfoCard.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/InfoCard/InfoCard.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/InfoCard/InfoCard.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/HeaderTabs/index.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/HeaderTabs/HeaderTabs.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/HeaderTabs/HeaderTabs.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/HeaderLabel/HeaderLabel.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/HeaderLabel/HeaderLabel.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/HeaderActionMenu/HeaderActionMenu.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/HeaderActionMenu/HeaderActionMenu.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Header/Header.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Header/Header.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Header/Header.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ErrorPage/MicDrop.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ErrorPage/ErrorPage.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ErrorPage/ErrorPage.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ErrorBoundary/ErrorBoundary.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ErrorBoundary/ErrorBoundary.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ContentHeader/ContentHeader.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/ContentHeader/ContentHeader.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Content/Content.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Breadcrumbs/Breadcrumbs.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Breadcrumbs/Breadcrumbs.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/Breadcrumbs/Breadcrumbs.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/BottomLink/BottomLink.tsx',
    '/Users/foo/backstage/packages/core-components/src/layout/BottomLink/BottomLink.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/icons/icons.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/WarningPanel/WarningPanel.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/WarningPanel/WarningPanel.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/WarningPanel/WarningPanel.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TrendLine/TrendLine.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TrendLine/TrendLine.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TrendLine/TrendLine.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Table/TableLoadingBody.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Table/Table.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Table/Table.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Table/Table.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Table/SubvalueCell.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Table/Filters.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TabbedLayout/TabbedLayout.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TabbedLayout/TabbedLayout.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TabbedLayout/TabbedLayout.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TabbedLayout/RoutedTabs.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/TabbedLayout/RoutedTabs.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/SupportButton/SupportButton.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/SupportButton/SupportButton.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/StructuredMetadataTable/index.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/StructuredMetadataTable/StructuredMetadataTable.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/StructuredMetadataTable/StructuredMetadataTable.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/StructuredMetadataTable/StructuredMetadataTable.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/StructuredMetadataTable/MetadataTable.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Status/Status.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Status/Status.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Status/Status.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/SimpleStepper/SimpleStepperStep.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/SimpleStepper/SimpleStepperFooter.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/SimpleStepper/SimpleStepper.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/SimpleStepper/SimpleStepper.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/SimpleStepper/SimpleStepper.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Select/index.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Select/Select.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Select/Select.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Select/Select.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Select/static/OpenedDropdown.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Select/static/ClosedDropdown.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ResponseErrorPanel/ResponseErrorPanel.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/LinearGauge.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/LinearGauge.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/LinearGauge.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/GaugeCard.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/GaugeCard.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/GaugeCard.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/Gauge.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/Gauge.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ProgressBars/Gauge.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Progress/Progress.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Progress/Progress.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Progress/Progress.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/OverflowTooltip/OverflowTooltip.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/OverflowTooltip/OverflowTooltip.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/OverflowTooltip/OverflowTooltip.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/OAuthRequestDialog/OAuthRequestDialog.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/OAuthRequestDialog/LoginRequestListItem.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/MarkdownContent/MarkdownContent.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/MarkdownContent/MarkdownContent.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/useLogViewerSelection.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/useLogViewerSelection.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/useLogViewerSearch.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/useLogViewerSearch.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/RealLogViewer.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/RealLogViewer.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/LogViewerControls.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/LogViewer.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/LogViewer.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/LogLine.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LogViewer/LogLine.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LinkButton/LinkButton.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LinkButton/LinkButton.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/LinkButton/LinkButton.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Link/Link.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Link/Link.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Link/Link.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Lifecycle/Lifecycle.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Lifecycle/Lifecycle.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Lifecycle/Lifecycle.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/HorizontalScrollGrid/index.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/HorizontalScrollGrid/HorizontalScrollGrid.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/HorizontalScrollGrid/HorizontalScrollGrid.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/HorizontalScrollGrid/HorizontalScrollGrid.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/HeaderIconLinkRow/IconLinkVertical.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/HeaderIconLinkRow/HeaderIconLinkRow.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/FeatureDiscovery/FeatureCalloutCircular.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/FeatureDiscovery/FeatureCalloutCircular.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ErrorPanel/ErrorPanel.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/ErrorPanel/ErrorPanel.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/EmptyState/MissingAnnotationEmptyState.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/EmptyState/EmptyStateImage.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/EmptyState/EmptyStateImage.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/EmptyState/EmptyState.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/EmptyState/EmptyState.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/EmptyState/EmptyState.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Drawer/Drawer.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DismissableBanner/DismissableBanner.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DismissableBanner/DismissableBanner.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DismissableBanner/DismissableBanner.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Dialog/Dialog.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/Node.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/Node.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/Edge.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/Edge.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/DependencyGraph.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/DependencyGraph.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/DependencyGraph.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/DefaultNode.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/DependencyGraph/DefaultLabel.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CreateButton/CreateButton.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CopyTextButton/index.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CopyTextButton/CopyTextButton.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CopyTextButton/CopyTextButton.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CopyTextButton/CopyTextButton.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CodeSnippet/index.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CodeSnippet/CodeSnippet.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CodeSnippet/CodeSnippet.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/CodeSnippet/CodeSnippet.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Chip/Chip.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Avatar/Avatar.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Avatar/Avatar.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/Avatar/Avatar.stories.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/AutoLogout/StillTherePrompt.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/AutoLogout/Autologout.test.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/AutoLogout/AutoLogout.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/AlertDisplay/AlertDisplay.tsx',
    '/Users/foo/backstage/packages/core-components/src/components/AlertDisplay/AlertDisplay.test.tsx',
  ],
  perfectResult: {},
}

export default backstage
