import { AutolinkingTestCase } from '../types'

const polarisReact: AutolinkingTestCase = {
  name: 'Polaris - react',
  passThreshold: 0.75, // most remaining failures due to lacking context
  figmaComponents: [
    { name: '.Mobile top bar', id: '111471:102036' },
    { name: '.slot examples', id: '111368:28722' },
    { name: '.domains-empty-state', id: '111320:34097' },
    { name: '.Screenshots', id: '111176:10398' },
    { name: '.Subcomponent header', id: '110918:22796' },
    { name: '.Component header', id: '110918:17606' },
    { name: '.Variant Detail', id: '107969:44241' },
    { name: '.Variant Title', id: '107969:44237' },
    { name: '.Spec header', id: '107969:44234' },
    { name: 'UI Shell', id: '111726:87471' },
    { name: 'Mobile device', id: '111471:101064' },
    { name: 'Country', id: '111377:33185' },
    { name: 'Slot', id: '108511:12346' },
    { name: 'Cursor', id: '84608:38801' },
    { name: 'Product image', id: '107922:1712' },
    { name: '.Grid', id: '56963:30933' },
    { name: '.Card', id: '84164:61609' },
    { name: '.Assets/Row', id: '84164:61469' },
    { name: '.Assets/Header', id: '84164:61450' },
    { name: '.Filters', id: '27668:11096' },
    { name: '.Layout', id: '78394:31942' },
    { name: '.Setting toggle', id: '77196:32435' },
    { name: '.Tabs legacy', id: '86562:46659' },
    { name: '.Assets/Tab legacy', id: '86562:46430' },
    { name: 'Video thumbnail', id: '109630:31250' },
    { name: 'Play button', id: '109630:31207' },
    { name: '.Play button', id: '67330:21527' },
    { name: '.Video thumbnail', id: '50769:21077' },
    { name: 'Top bar', id: '109785:19170' },
    { name: 'Sidekick', id: '109785:19597' },
    { name: 'Secondary menu', id: '109785:19581' },
    { name: 'Right content', id: '111489:106090' },
    { name: 'Logo', id: '109785:19525' },
    { name: 'Search field', id: '109785:19497' },
    { name: 'User menu', id: '109785:19481' },
    { name: 'Nav toggle', id: '111489:106398' },
    { name: '.Assets / Sidekick button', id: '81750:31329' },
    { name: '.Assets / Alerts button', id: '81750:31068' },
    { name: '.Top bar', id: '28822:336' },
    { name: '.Assets/Logo', id: '112354:366' },
    { name: '.Assets/Store switcher', id: '29236:14848' },
    { name: '.Assets/Search field', id: '28822:175' },
    { name: '.Assets/Store menu button', id: '28822:309' },
    { name: '.Assets/Nav toggle', id: '463:3086' },
    { name: 'Tooltip', id: '110065:49636' },
    { name: '.Assets/Tail', id: '109814:45727' },
    { name: '.Tooltip', id: '109814:45676' },
    { name: 'Toast', id: '108524:15659' },
    { name: '.Toast', id: '29653:21166' },
    { name: 'Thumbnail', id: '109135:42783' },
    { name: '.Thumbnail', id: '27579:4928' },
    { name: 'Text field', id: '108407:11851' },
    { name: 'Segment bottom', id: '108462:8505' },
    { name: 'Segment top', id: '108462:8360' },
    { name: 'Stepper', id: '108462:8487' },
    { name: 'Suffix', id: '108407:11452' },
    { name: 'Prefix', id: '108407:11457' },
    { name: 'Multiline field', id: '108420:1346' },
    { name: 'Number field', id: '108462:8059' },
    { name: '.text field', id: '29426:139' },
    { name: '.number field', id: '52267:23042' },
    { name: '.multiline text field', id: '52267:23224' },
    { name: '.assets/Prefix', id: '51903:22671' },
    { name: '.assets/Suffix', id: '51903:22664' },
    { name: '.assets/Stepper', id: '28915:15180' },
    { name: '.assets/Input', id: '28915:15501' },
    { name: 'Tag', id: '109012:41728' },
    { name: 'Remove button', id: '108973:33251' },
    { name: '.Tag', id: '27579:4688' },
    { name: '.Removable tag', id: '51536:23822' },
    { name: '.Clickable tag', id: '51536:23867' },
    { name: 'Tabs', id: '110386:1423' },
    { name: 'Tab', id: '110371:90046' },
    { name: 'Disclosure tab', id: '110371:91554' },
    { name: 'Icon only', id: '110371:90077' },
    { name: 'Mobile/Tabs', id: '110386:1832' },
    { name: 'Tab', id: '110386:1794' },
    { name: 'Disclosure tab', id: '110386:1778' },
    { name: 'Icon only', id: '110386:1771' },
    { name: '.Tabs', id: '84001:38965' },
    { name: '.Assets/Tab', id: '84001:38745' },
    { name: 'Spinner', id: '109103:28058' },
    { name: 'Animation', id: '109103:27976' },
    { name: '.Spinner', id: '27579:4687' },
    { name: 'Skeleton thumbnail', id: '62007:21648' },
    { name: 'Skeleton display text', id: '62007:21531' },
    { name: 'Skeleton body text', id: '62007:21609' },
    { name: 'Select', id: '108526:14477' },
    { name: 'Input text', id: '108611:1968' },
    { name: '.select', id: '29402:14771' },
    { name: '.assets/Help text/Default', id: '51521:23138' },
    { name: '.assets/Select field', id: '29281:14870' },
    { name: 'Resource list', id: '110491:47135' },
    { name: 'Resource header', id: '110491:46855' },
    { name: 'Item with shortcut action', id: '110491:50540' },
    { name: 'Item', id: '110491:36572' },
    { name: 'Mobile/Resource list', id: '111025:10258' },
    { name: 'Item', id: '110944:6122' },
    { name: '.Resource list', id: '53484:22500' },
    { name: '.Assets/Header', id: '53457:26770' },
    { name: '.Resource Item', id: '53359:25889' },
    { name: 'Range slider', id: '109643:22164' },
    { name: 'Thumb', id: '109304:4612' },
    { name: '.Range slider', id: '28915:14403' },
    { name: '.Assets/Slider', id: '51161:21809' },
    { name: '.Assets/Thumb', id: '28915:14395' },
    { name: 'Radio button', id: '108368:2270' },
    { name: '.assets/Help text', id: '50733:21486' },
    { name: '.radio button with label', id: '27648:7547' },
    { name: '.radio button', id: '27648:7332' },
    { name: 'Progress bar', id: '27579:4563' },
    { name: 'Popover', id: '110421:9260' },
    { name: '.Popover', id: '29461:2488' },
    { name: 'Pagination', id: '108807:10772' },
    { name: 'Next button', id: '109134:14508' },
    { name: 'Previous button', id: '108807:10757' },
    { name: '.Pagination', id: '29604:275' },
    { name: '.Assets/Pagination', id: '27579:4558' },
    { name: 'Page actions', id: '108807:15671' },
    { name: '.Page actions', id: '27579:4555' },
    { name: 'Page', id: '111691:69452' },
    { name: 'Header', id: '111691:53161' },
    { name: 'Actions', id: '111691:49869' },
    { name: 'Secondary action', id: '110065:29772' },
    { name: '.Page', id: '29461:862' },
    { name: '.Apps', id: '50358:21280' },
    { name: '.Marketing', id: '50358:21192' },
    { name: '.Analytics', id: '50343:22256' },
    { name: '.Finances', id: '50343:21983' },
    { name: '.Customers', id: '50294:21556' },
    { name: '.Products', id: '50267:23178' },
    { name: '.Orders', id: '50257:20692' },
    { name: '.Assets/Picker', id: '105937:3862' },
    { name: '.Assets/Secondary action', id: '29461:405' },
    { name: '.Assets/Actions', id: '50175:20678' },
    { name: 'Option list', id: '109368:18066' },
    { name: 'Option item', id: '109368:18196' },
    { name: '.Option list', id: '29413:20540' },
    { name: '.Assets/Option item', id: '29413:20275' },
    { name: 'Navigation', id: '109776:121231' },
    { name: 'Mobile/Navigation', id: '110015:22901' },
    { name: 'Section title', id: '109776:59846' },
    { name: 'Indicator', id: '109557:3763' },
    { name: 'Child item', id: '109776:99624' },
    { name: 'Parent item', id: '109776:99486' },
    { name: 'Home', id: '110015:21471' },
    { name: 'Discounts', id: '110015:22199' },
    { name: 'Shop', id: '110015:22463' },
    { name: 'Settings', id: '110015:21387' },
    { name: 'Email', id: '109834:130935' },
    { name: 'Point of sale', id: '109834:128562' },
    { name: 'Online store', id: '109834:128450' },
    { name: 'Marketing', id: '109821:122273' },
    { name: 'Analytics', id: '109821:122187' },
    { name: 'Finances', id: '109821:121519' },
    { name: 'Content', id: '109821:121434' },
    { name: 'Customers', id: '109776:119185' },
    { name: 'Products', id: '109821:121349' },
    { name: 'Orders', id: '109776:119162' },
    { name: '.Mobile/Subcomponents/Section title', id: '110015:19647' },
    { name: '.Mobile/Subcomponents/Child item', id: '110015:19623' },
    { name: '.Mobile/Subcomponents/Parent item', id: '110015:19563' },
    { name: '.Assets/Section title', id: '68778:30923' },
    { name: '.Navigation', id: '29410:38339' },
    { name: '.Assets/Items', id: '29402:14828' },
    { name: 'Modal', id: '111368:23985' },
    { name: 'Footer', id: '108974:9575' },
    { name: 'Title bar', id: '108943:4401' },
    { name: '.Assets/Header', id: '31716:59' },
    { name: '.Modal', id: '28348:17068' },
    { name: 'Media card', id: '109745:85696' },
    { name: '.Media card', id: '27579:3745' },
    { name: 'Lisbox', id: '111674:1339' },
    { name: 'Option', id: '111606:72844' },
    { name: 'Action', id: '111596:71602' },
    { name: 'Header', id: '111674:30439' },
    { name: 'Link', id: '108808:30098' },
    { name: '.Link', id: '51555:21010' },
    { name: 'Keyboard key', id: '110000:10862' },
    { name: '.Keyboard key', id: '84172:42079' },
    { name: 'Inline error', id: '28210:12203' },
    { name: 'Index table', id: '111680:45555' },
    { name: 'Mobile/Index table', id: '111720:37938' },
    { name: '.Mobile/Subcomponents/Row', id: '111720:36964' },
    { name: 'Footer', id: '111720:38284' },
    { name: 'Selection count row', id: '111612:75208' },
    { name: 'Horizontal scroll bar', id: '110641:62520' },
    { name: 'Bulk actions', id: '110641:64122' },
    { name: 'Sort icon', id: '110421:26662' },
    { name: 'Column reorder', id: '111612:64433' },
    { name: 'Column', id: '110421:25965' },
    { name: 'Index cell', id: '110421:25820' },
    { name: 'Index header cell', id: '110421:25812' },
    { name: '.Filter pill', id: '110912:39848' },
    { name: '.Filter pill', id: '68605:33198' },
    { name: '.Assets / Column reorder', id: '68412:37925' },
    { name: '.Assets/Bulk actions', id: '67296:23823' },
    { name: '.Assets/Sort icon', id: '67238:23155' },
    { name: '.Index filtering', id: '110421:26501' },
    { name: '.Index filtering', id: '67128:21676' },
    { name: '.Index table', id: '45017:32955' },
    { name: '.Assets/Column', id: '44707:19605' },
    { name: '.Assets/Cell/Table cell', id: '44707:19591' },
    { name: '.Assets/Cell/Header cell', id: '44707:19586' },
    { name: '.Assets/Small screen row', id: '45051:22536' },
    { name: 'Index filter', id: '110912:43515' },
    { name: 'Mobile/Index filter', id: '111358:31613' },
    { name: '.Mobile/Subcomponents/Controls', id: '111187:36083' },
    { name: 'Controls', id: '111028:39573' },
    { name: 'Footer help', id: '108808:30394' },
    { name: '.Footer help', id: '27579:4554' },
    { name: 'Fullscreen bar', id: '110000:10540' },
    { name: '.Fullscreem bar', id: '71205:18753' },
    { name: 'Filters', id: '111407:92131' },
    { name: 'Mobile/Filters', id: '111720:35800' },
    { name: 'Filters Bar', id: '111562:48065' },
    { name: 'Filter pill', id: '111058:33366' },
    { name: 'Add filter', id: '111058:33314' },
    { name: '.Filter pill', id: '110421:26830' },
    { name: 'Exception list', id: '108933:30513' },
    { name: '.Exception list', id: '27579:4537' },
    { name: 'Empty state', id: '109979:8183' },
    { name: 'Illustration', id: '111306:33428' },
    { name: '.Assets/Spot Illustration', id: '12979:10119' },
    { name: '.Assets/Illustration', id: '49495:19719' },
    { name: '.Empty state', id: '27579:4461' },
    { name: 'Drop zone', id: '109178:44479' },
    { name: '.Drop zone', id: '27579:4342' },
    { name: 'Divider', id: '109745:84282' },
    { name: '.Divider', id: '73002:33613' },
    { name: 'Description list', id: '109630:30271' },
    { name: 'List item', id: '109630:30179' },
    { name: '.Description list', id: '53638:30530' },
    { name: '.Assets/List item', id: '53638:30483' },
    { name: 'DatePicker', id: '108914:2585' },
    { name: 'Month', id: '108797:52863' },
    { name: 'Day of week', id: '108797:52864' },
    { name: 'Day', id: '108797:54548' },
    { name: 'Day', id: '108797:52832' },
    { name: 'Range calendar', id: '108797:55823' },
    { name: 'Base calendar', id: '108797:55720' },
    { name: '.Assets/Month', id: '68742:21620' },
    { name: '.Assets/Day of week', id: '51054:21537' },
    { name: '.Assets/Date', id: '51054:21522' },
    { name: '.Date picker', id: '27668:11405' },
    { name: 'Data table', id: '111636:2477' },
    { name: 'Mobile/Data table', id: '111683:79795' },
    { name: 'Footer', id: '111683:63838' },
    { name: 'Navigation', id: '111683:62772' },
    { name: 'Column', id: '111636:2490' },
    { name: 'Cell', id: '111636:2455' },
    { name: 'Totals', id: '111636:2430' },
    { name: 'Heading', id: '111636:2394' },
    { name: '.Assets/Table footer', id: '8307:12310' },
    { name: '.Assets/Table row', id: '53538:27024' },
    { name: '.Assets/Header/Cell', id: '53538:25532' },
    { name: '.Assets/Table header', id: '53538:25524' },
    { name: '.Data table', id: '27800:2137' },
    { name: '.Assets/Mobile only/Navigation', id: '8392:16389' },
    { name: '.Assets/Totals row', id: '27668:13612' },
    { name: 'Contextual save bar', id: '108458:10011' },
    { name: '.Contextual save bar', id: '27579:4250' },
    { name: 'Color picker', id: '108433:7829' },
    { name: '.Color picker', id: '27579:730' },
    { name: 'Choice list', id: '109134:7785' },
    { name: '.choice list', id: '28210:21889' },
    { name: 'Checkbox', id: '108368:1341' },
    { name: '.assets/Help text', id: '50716:21060' },
    { name: '.checkbox with label', id: '27579:515' },
    { name: '.Checkbox', id: '27579:728' },
    { name: 'Card', id: '109372:20170' },
    { name: '.Assets/Section title', id: '105343:2566' },
    { name: '.Assets/Card title', id: '94021:80366' },
    { name: '.Card examples', id: '75727:32170' },
    { name: '.Card alpha', id: '75727:32130' },
    { name: 'Callout card', id: '109313:7455' },
    { name: 'Illustration', id: '111176:4158' },
    { name: '.Assets', id: '93027:59250' },
    { name: '.Callout card', id: '84164:64397' },
    { name: '.Assets/Illustration', id: '49245:19864' },
    { name: 'Button group segmented', id: '109118:3325' },
    { name: 'Button group', id: '108782:4042' },
    { name: '.Button group', id: '27566:7963' },
    { name: 'Button', id: '108641:35692' },
    { name: 'Icon button', id: '108666:39153' },
    { name: '.button-shine', id: '108666:37138' },
    { name: '.Default button', id: '53964:22768' },
    { name: '.Primary button', id: '53964:22769' },
    { name: '.Tertiary button', id: '53971:23149' },
    { name: '.Tertiary critical button', id: '83656:36193' },
    { name: '.Critical button', id: '83656:36204' },
    { name: '.Plain button', id: '83637:53940' },
    { name: '.Plain critical button', id: '84120:42002' },
    { name: '.Plain monochrome', id: '84129:49491' },
    { name: '.Primary critical button', id: '53964:22800' },
    { name: '.Primary success button', id: '83621:48297' },
    { name: '.Icon button', id: '84375:42685' },
    { name: '.Split button', id: '97516:71658' },
    { name: 'Banner', id: '109293:4284' },
    { name: '.Banner', id: '83621:42265' },
    { name: '.Banner with no title', id: '85796:58679' },
    { name: 'Badge', id: '108227:921' },
    { name: 'Progress Indicator', id: '108227:892' },
    { name: '.Badge', id: '26521:97' },
    { name: '.Assets/Progress', id: '26521:136' },
    { name: 'Avatar', id: '107957:44068' },
    { name: '.Avatar + label', id: '87434:46985' },
    { name: '.avatar', id: '87434:46824' },
    { name: 'Action List', id: '108977:15501' },
    { name: 'Section', id: '108224:8280' },
    { name: 'Destructive item', id: '108180:1430' },
    { name: 'Item', id: '108154:1050' },
    { name: '.Action list', id: '29413:20122' },
    { name: '.Assets/Items', id: '26376:6454' },
    { name: 'Account Connection', id: '109630:23132' },
    { name: '.Account connection', id: '26497:388' },
  ],
  filepathExports: [
    '/Users/foo/polaris/polaris-react/src/components/VideoThumbnail/VideoThumbnail.tsx~VideoThumbnail',
    '/Users/foo/polaris/polaris-react/src/components/VideoThumbnail/VideoThumbnail.tsx~VideoThumbnailProps',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledLink/UnstyledLink.tsx~UnstyledLinkProps',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledLink/UnstyledLink.tsx~UnstyledLink',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledButton/utils.tsx~unstyledButtonFrom',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledButton/UnstyledButton.tsx~UnstyledButton',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledButton/UnstyledButton.tsx~UnstyledButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/Truncate/Truncate.tsx~Truncate',
    '/Users/foo/polaris/polaris-react/src/components/Truncate/Truncate.tsx~TruncateProps',
    '/Users/foo/polaris/polaris-react/src/components/TrapFocus/TrapFocus.tsx~TrapFocus',
    '/Users/foo/polaris/polaris-react/src/components/TrapFocus/TrapFocus.tsx~TrapFocusProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.tsx~UserMenuProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.tsx~SearchFieldProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.tsx~TopBarProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.tsx~TopBar',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx~UserMenu',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx~UserMenuProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchField/SearchField.tsx~SearchField',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchField/SearchField.tsx~SearchFieldProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.tsx~SearchDismissOverlay',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Search/Search.tsx~Search',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Search/Search.tsx~SearchProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/Menu.tsx~Menu',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/Menu.tsx~MenuProps',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/components/Message/Message.tsx~Message',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/components/Message/Message.tsx~MessageProps',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx~Tooltip',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx~Width',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx~Padding',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx~BorderRadius',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx~TooltipProps',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx~TooltipOverlay',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx~TooltipOverlayProps',
    '/Users/foo/polaris/polaris-react/src/components/Toast/Toast.tsx~ToastProps',
    '/Users/foo/polaris/polaris-react/src/components/Toast/Toast.tsx~Toast',
    '/Users/foo/polaris/polaris-react/src/components/Thumbnail/Thumbnail.tsx~Thumbnail',
    '/Users/foo/polaris/polaris-react/src/components/Thumbnail/Thumbnail.tsx~ThumbnailProps',
    '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.tsx~TextField',
    '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.tsx~MutuallyExclusiveSelectionProps',
    '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.tsx~MutuallyExclusiveInteractionProps',
    '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.tsx~TextFieldProps',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Spinner/Spinner.tsx~SpinnerProps',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Spinner/Spinner.tsx~Spinner',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Resizer/Resizer.tsx~Resizer',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Resizer/Resizer.tsx~ResizerProps',
    '/Users/foo/polaris/polaris-react/src/components/TextContainer/TextContainer.tsx~TextContainer',
    '/Users/foo/polaris/polaris-react/src/components/TextContainer/TextContainer.tsx~TextContainerProps',
    '/Users/foo/polaris/polaris-react/src/components/Text/Text.tsx~TextProps',
    '/Users/foo/polaris/polaris-react/src/components/Text/Text.tsx~Text',
    '/Users/foo/polaris/polaris-react/src/components/Tag/Tag.tsx~Tag',
    '/Users/foo/polaris/polaris-react/src/components/Tag/Tag.tsx~NonMutuallyExclusiveProps',
    '/Users/foo/polaris/polaris-react/src/components/Tag/Tag.tsx~TagProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/Tabs.tsx~TabsState',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/Tabs.tsx~TabsProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/Tabs.tsx~Tabs',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx~TabMeasurerProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx~TabMeasurer',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/Tab.tsx~Tab',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/RenameModal/RenameModal.tsx~RenameModal',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/RenameModal/RenameModal.tsx~RenameModalProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/DuplicateModal/DuplicateModal.tsx~DuplicateModal',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/DuplicateModal/DuplicateModal.tsx~DuplicateModalProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Panel/Panel.tsx~Panel',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Panel/Panel.tsx~PanelProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/List/List.tsx~List',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/List/List.tsx~ListProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Item/Item.tsx~ItemProps',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/CreateViewModal/CreateViewModal.tsx~CreateViewModal',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/CreateViewModal/CreateViewModal.tsx~CreateViewModalProps',
    '/Users/foo/polaris/polaris-react/src/components/Sticky/Sticky.tsx~Sticky',
    '/Users/foo/polaris/polaris-react/src/components/Sticky/Sticky.tsx~StickyProps',
    '/Users/foo/polaris/polaris-react/src/components/Spinner/Spinner.tsx~Spinner',
    '/Users/foo/polaris/polaris-react/src/components/Spinner/Spinner.tsx~SpinnerProps',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx~SkeletonThumbnail',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx~SkeletonThumbnailProps',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonTabs/SkeletonTabs.tsx~SkeletonTabs',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonTabs/SkeletonTabs.tsx~SkeletonTabsProps',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonPage/SkeletonPage.tsx~SkeletonPage',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonPage/SkeletonPage.tsx~SkeletonPageProps',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.tsx~SkeletonDisplayText',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.tsx~SkeletonDisplayTextProps',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.tsx~SkeletonBodyText',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.tsx~SkeletonBodyTextProps',
    '/Users/foo/polaris/polaris-react/src/components/Sheet/Sheet.tsx~Sheet',
    '/Users/foo/polaris/polaris-react/src/components/Sheet/Sheet.tsx~SheetProps',
    '/Users/foo/polaris/polaris-react/src/components/ShadowBevel/ShadowBevel.tsx~ShadowBevel',
    '/Users/foo/polaris/polaris-react/src/components/ShadowBevel/ShadowBevel.tsx~ShadowBevelProps',
    '/Users/foo/polaris/polaris-react/src/components/SettingToggle/SettingToggle.tsx~SettingToggle',
    '/Users/foo/polaris/polaris-react/src/components/SettingToggle/SettingToggle.tsx~SettingToggleProps',
    '/Users/foo/polaris/polaris-react/src/components/SettingAction/SettingAction.tsx~SettingAction',
    '/Users/foo/polaris/polaris-react/src/components/SettingAction/SettingAction.tsx~SettingActionProps',
    '/Users/foo/polaris/polaris-react/src/components/SelectAllActions/SelectAllActions.tsx~SelectAllActionsProps',
    '/Users/foo/polaris/polaris-react/src/components/SelectAllActions/SelectAllActions.tsx~SelectAllActions',
    '/Users/foo/polaris/polaris-react/src/components/Select/Select.tsx~Select',
    '/Users/foo/polaris/polaris-react/src/components/Select/Select.tsx~SelectOption',
    '/Users/foo/polaris/polaris-react/src/components/Select/Select.tsx~SelectGroup',
    '/Users/foo/polaris/polaris-react/src/components/Select/Select.tsx~SelectProps',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/Scrollable.tsx~ScrollableProps',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/Scrollable.tsx~ScrollToOptions',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/Scrollable.tsx~ScrollableRef',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/Scrollable.tsx~Scrollable',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/components/ScrollTo/ScrollTo.tsx~ScrollTo',
    '/Users/foo/polaris/polaris-react/src/components/ResourceList/ResourceList.tsx~ResourceList',
    '/Users/foo/polaris/polaris-react/src/components/ResourceList/ResourceList.tsx~ResourceListPaginationProps',
    '/Users/foo/polaris/polaris-react/src/components/ResourceList/ResourceList.tsx~ResourceListProps',
    '/Users/foo/polaris/polaris-react/src/components/ResourceItem/ResourceItem.tsx~ResourceItem',
    '/Users/foo/polaris/polaris-react/src/components/ResourceItem/ResourceItem.tsx~ResourceItemProps',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/RangeSlider.tsx~RangeSlider',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/RangeSlider.tsx~RangeSliderProps',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx~SingleThumb',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx~SingleThumbProps',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.tsx~DualThumbProps',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.tsx~DualThumb',
    '/Users/foo/polaris/polaris-react/src/components/RadioButton/RadioButton.tsx~RadioButton',
    '/Users/foo/polaris/polaris-react/src/components/RadioButton/RadioButton.tsx~RadioButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/ProgressBar/ProgressBar.tsx~ProgressBar',
    '/Users/foo/polaris/polaris-react/src/components/ProgressBar/ProgressBar.tsx~ProgressBarProps',
    '/Users/foo/polaris/polaris-react/src/components/PositionedOverlay/PositionedOverlay.tsx~PositionedOverlayProps',
    '/Users/foo/polaris/polaris-react/src/components/PositionedOverlay/PositionedOverlay.tsx~PositionedOverlay',
    '/Users/foo/polaris/polaris-react/src/components/PortalsManager/PortalsManager.tsx~PortalsManager',
    '/Users/foo/polaris/polaris-react/src/components/PortalsManager/PortalsManager.tsx~PortalsManagerProps',
    '/Users/foo/polaris/polaris-react/src/components/PortalsManager/components/PortalsContainer/PortalsContainer.tsx~PolarisContainerProps',
    '/Users/foo/polaris/polaris-react/src/components/PortalsManager/components/PortalsContainer/PortalsContainer.tsx~PortalsContainer',
    '/Users/foo/polaris/polaris-react/src/components/Portal/Portal.tsx~Portal',
    '/Users/foo/polaris/polaris-react/src/components/Portal/Portal.tsx~PortalProps',
    '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx~PopoverCloseSource',
    '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx~PopoverAutofocusTarget',
    '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx~PopoverProps',
    '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx~PopoverPublicAPI',
    '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx~Popover',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Section/Section.tsx~Section',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Section/Section.tsx~SectionProps',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx~nodeContainsDescendant',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx~PopoverCloseSource',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx~PopoverAutofocusTarget',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx~PopoverOverlayProps',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx~PopoverOverlay',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Pane/Pane.tsx~Pane',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Pane/Pane.tsx~PaneProps',
    '/Users/foo/polaris/polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx~PolarisTestProvider',
    '/Users/foo/polaris/polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx~WithPolarisTestProviderOptions',
    '/Users/foo/polaris/polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx~PolarisTestProviderProps',
    '/Users/foo/polaris/polaris-react/src/components/Pagination/Pagination.tsx~Pagination',
    '/Users/foo/polaris/polaris-react/src/components/Pagination/Pagination.tsx~PaginationProps',
    '/Users/foo/polaris/polaris-react/src/components/PageActions/PageActions.tsx~PageActions',
    '/Users/foo/polaris/polaris-react/src/components/PageActions/PageActions.tsx~PageActionsProps',
    '/Users/foo/polaris/polaris-react/src/components/Page/Page.tsx~Page',
    '/Users/foo/polaris/polaris-react/src/components/Page/Page.tsx~PageProps',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/Header.tsx~Header',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/Header.tsx~HeaderProps',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/components/Title/Title.tsx~Title',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/components/Title/Title.tsx~TitleProps',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/OptionList.tsx~OptionList',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/OptionList.tsx~OptionListProps',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/components/Option/Option.tsx~Option',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/components/Option/Option.tsx~OptionProps',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/context.tsx~NavigationContext',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/Navigation.tsx~NavigationProps',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/Navigation.tsx~Navigation',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Section/Section.tsx~Section',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Section/Section.tsx~SectionProps',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/Item.tsx~ItemSecondaryAction',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/Item.tsx~isNavigationItemActive',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/Item.tsx~MAX_SECONDARY_ACTIONS',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/components/SecondaryNavigation/SecondaryNavigation.tsx~SecondaryNavigation',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/components/SecondaryNavigation/SecondaryNavigation.tsx~SecondaryNavigationProps',
    '/Users/foo/polaris/polaris-react/src/components/Modal/Modal.tsx~ModalSize',
    '/Users/foo/polaris/polaris-react/src/components/Modal/Modal.tsx~ModalProps',
    '/Users/foo/polaris/polaris-react/src/components/Modal/Modal.tsx~Modal',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Section/Section.tsx~Section',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Section/Section.tsx~SectionProps',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Header/Header.tsx~Header',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Header/Header.tsx~HeaderProps',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Footer/Footer.tsx~Footer',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Footer/Footer.tsx~FooterProps',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Dialog/Dialog.tsx~Dialog',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Dialog/Dialog.tsx~DialogProps',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/CloseButton/CloseButton.tsx~CloseButton',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/CloseButton/CloseButton.tsx~CloseButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/MessageIndicator/MessageIndicator.tsx~MessageIndicator',
    '/Users/foo/polaris/polaris-react/src/components/MessageIndicator/MessageIndicator.tsx~MessageIndicatorProps',
    '/Users/foo/polaris/polaris-react/src/components/MediaQueryProvider/MediaQueryProvider.tsx~MediaQueryProvider',
    '/Users/foo/polaris/polaris-react/src/components/MediaCard/MediaCard.tsx~MediaCard',
    '/Users/foo/polaris/polaris-react/src/components/Loading/Loading.tsx~LoadingProps',
    '/Users/foo/polaris/polaris-react/src/components/Loading/Loading.tsx~Loading',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.tsx~Listbox',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.tsx~AutoSelection',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.tsx~ListboxProps',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.tsx~ArrowKeys',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/TextOption/TextOption.tsx~TextOptionProps',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/TextOption/TextOption.tsx~TextOption',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Section/Section.tsx~Section',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Option/Option.tsx~OptionProps',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Option/Option.tsx~Option',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Loading/Loading.tsx~LoadingProps',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Loading/Loading.tsx~Loading',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Header/Header.tsx~Header',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Action/Action.tsx~Action',
    '/Users/foo/polaris/polaris-react/src/components/List/List.tsx~ListProps',
    '/Users/foo/polaris/polaris-react/src/components/List/List.tsx~List',
    '/Users/foo/polaris/polaris-react/src/components/List/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/List/components/Item/Item.tsx~ItemProps',
    '/Users/foo/polaris/polaris-react/src/components/Link/Link.tsx~Link',
    '/Users/foo/polaris/polaris-react/src/components/Link/Link.tsx~LinkProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/LegacyTabs.tsx~LegacyTabs',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/LegacyTabs.tsx~LegacyTabsProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/TabMeasurer/TabMeasurer.tsx~TabMeasurerProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/TabMeasurer/TabMeasurer.tsx~TabMeasurer',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Tab/Tab.tsx~Tab',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Tab/Tab.tsx~TabProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Panel/Panel.tsx~Panel',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Panel/Panel.tsx~PanelProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/List/List.tsx~List',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/List/List.tsx~ListProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Item/Item.tsx~ItemProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/LegacyStack.tsx~LegacyStackProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/LegacyStack.tsx~LegacyStack',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/components/Item/Item.tsx~LegacyItemProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/LegacyFilters.tsx~LegacyFilters',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/LegacyFilters.tsx~AppliedFilterInterface',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/LegacyFilters.tsx~FilterInterface',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/LegacyFilters.tsx~LegacyFiltersProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/TagsWrapper/TagsWrapper.tsx~TagsWrapper',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.tsx~ConnectedFilterControlProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.tsx~ConnectedFilterControl',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/LegacyCard.tsx~LegacyCardSectionProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/LegacyCard.tsx~LegacyCardHeaderProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/LegacyCard.tsx~LegacyCardSubsectionProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/LegacyCard.tsx~LegacyCardProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/LegacyCard.tsx~LegacyCard',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Subsection/Subsection.tsx~Subsection',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Subsection/Subsection.tsx~LegacyCardSubsectionProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Section/Section.tsx~Section',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Section/Section.tsx~LegacyCardSectionProps',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Header/Header.tsx~Header',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Header/Header.tsx~LegacyCardHeaderProps',
    '/Users/foo/polaris/polaris-react/src/components/Layout/Layout.tsx~LayoutProps',
    '/Users/foo/polaris/polaris-react/src/components/Layout/Layout.tsx~Layout',
    '/Users/foo/polaris/polaris-react/src/components/Layout/components/Section/Section.tsx~Section',
    '/Users/foo/polaris/polaris-react/src/components/Layout/components/Section/Section.tsx~SectionProps',
    '/Users/foo/polaris/polaris-react/src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx~AnnotatedSection',
    '/Users/foo/polaris/polaris-react/src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx~AnnotatedSectionProps',
    '/Users/foo/polaris/polaris-react/src/components/Labelled/Labelled.tsx~Labelled',
    '/Users/foo/polaris/polaris-react/src/components/Labelled/Labelled.tsx~errorID',
    '/Users/foo/polaris/polaris-react/src/components/Labelled/Labelled.tsx~helpTextID',
    '/Users/foo/polaris/polaris-react/src/components/Labelled/Labelled.tsx~labelID',
    '/Users/foo/polaris/polaris-react/src/components/Labelled/Labelled.tsx~LabelledProps',
    '/Users/foo/polaris/polaris-react/src/components/Label/Label.tsx~labelID',
    '/Users/foo/polaris/polaris-react/src/components/Label/Label.tsx~Label',
    '/Users/foo/polaris/polaris-react/src/components/Label/Label.tsx~LabelProps',
    '/Users/foo/polaris/polaris-react/src/components/KeypressListener/KeypressListener.tsx~KeypressListener',
    '/Users/foo/polaris/polaris-react/src/components/KeypressListener/KeypressListener.tsx~NonMutuallyExclusiveProps',
    '/Users/foo/polaris/polaris-react/src/components/KeypressListener/KeypressListener.tsx~KeypressListenerProps',
    '/Users/foo/polaris/polaris-react/src/components/KeyboardKey/KeyboardKey.tsx~KeyboardKey',
    '/Users/foo/polaris/polaris-react/src/components/KeyboardKey/KeyboardKey.tsx~KeyboardKeyProps',
    '/Users/foo/polaris/polaris-react/src/components/InlineStack/InlineStack.tsx~InlineStackProps',
    '/Users/foo/polaris/polaris-react/src/components/InlineStack/InlineStack.tsx~InlineStack',
    '/Users/foo/polaris/polaris-react/src/components/InlineGrid/InlineGrid.tsx~InlineGrid',
    '/Users/foo/polaris/polaris-react/src/components/InlineGrid/InlineGrid.tsx~InlineGridProps',
    '/Users/foo/polaris/polaris-react/src/components/InlineError/InlineError.tsx~InlineError',
    '/Users/foo/polaris/polaris-react/src/components/InlineError/InlineError.tsx~errorTextID',
    '/Users/foo/polaris/polaris-react/src/components/InlineError/InlineError.tsx~InlineErrorProps',
    '/Users/foo/polaris/polaris-react/src/components/InlineCode/InlineCode.tsx~InlineCodeProps',
    '/Users/foo/polaris/polaris-react/src/components/InlineCode/InlineCode.tsx~InlineCode',
    '/Users/foo/polaris/polaris-react/src/components/Indicator/Indicator.tsx~Indicator',
    '/Users/foo/polaris/polaris-react/src/components/Indicator/Indicator.tsx~IndicatorProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~IndexTable',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~IndexTableHeading',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~IndexTableSortDirection',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~IndexTablePaginationProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~IndexTableBaseProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~TableHeadingRect',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~IndexTableProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/ScrollContainer/ScrollContainer.tsx~ScrollContainer',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/ScrollContainer/ScrollContainer.tsx~ScrollContainerProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Row/Row.tsx~RowProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Row/Row.tsx~Row',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Checkbox/Checkbox.tsx~CheckboxWrapper',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Checkbox/Checkbox.tsx~Checkbox',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Cell/Cell.tsx~CellProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Cell/Cell.tsx~Cell',
    '/Users/foo/polaris/polaris-react/src/components/IndexProvider/IndexProvider.tsx~IndexProvider',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/IndexFilters.tsx~IndexFilters',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/IndexFilters.tsx~IndexFiltersProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/hooks/useSetIndexFiltersMode/useSetIndexFiltersMode.tsx~useSetIndexFiltersMode',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/UpdateButtons/UpdateButtons.tsx~UpdateButtons',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/UpdateButtons/UpdateButtons.tsx~UpdateButtonsProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/SortButton.tsx~SortButton',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/SortButton.tsx~SortButtonDirection',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/SortButton.tsx~SortButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/components/DirectionButton/DirectionButton.tsx~DirectionButton',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/components/DirectionButton/DirectionButton.tsx~DirectionButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.tsx~SearchFilterButton',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.tsx~SearchFilterButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/EditColumnsButton/EditColumnsButton.tsx~EditColumnsButton',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/EditColumnsButton/EditColumnsButton.tsx~EditColumnsButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/Container/Container.tsx~ContainerProps',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/Container/Container.tsx~Container',
    '/Users/foo/polaris/polaris-react/src/components/Image/Image.tsx~Image',
    '/Users/foo/polaris/polaris-react/src/components/Image/Image.tsx~ImageProps',
    '/Users/foo/polaris/polaris-react/src/components/Icon/Icon.tsx~Icon',
    '/Users/foo/polaris/polaris-react/src/components/Icon/Icon.tsx~IconProps',
    '/Users/foo/polaris/polaris-react/src/components/Grid/Grid.tsx~formatAreas',
    '/Users/foo/polaris/polaris-react/src/components/Grid/Grid.tsx~GridProps',
    '/Users/foo/polaris/polaris-react/src/components/Grid/Grid.tsx~Grid',
    '/Users/foo/polaris/polaris-react/src/components/Grid/components/Cell/Cell.tsx~Cell',
    '/Users/foo/polaris/polaris-react/src/components/Grid/components/Cell/Cell.tsx~CellProps',
    '/Users/foo/polaris/polaris-react/src/components/FullscreenBar/FullscreenBar.tsx~FullscreenBar',
    '/Users/foo/polaris/polaris-react/src/components/FullscreenBar/FullscreenBar.tsx~FullscreenBarProps',
    '/Users/foo/polaris/polaris-react/src/components/Frame/Frame.tsx~Frame',
    '/Users/foo/polaris/polaris-react/src/components/Frame/Frame.tsx~FrameProps',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ToastManager/ToastManager.tsx~ToastManagerProps',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ToastManager/ToastManager.tsx~ToastManager',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Toast/Toast.tsx~Toast',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Toast/Toast.tsx~ToastProps',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Toast/Toast.tsx~DEFAULT_TOAST_DURATION',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Toast/Toast.tsx~DEFAULT_TOAST_DURATION_WITH_ACTION',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Loading/Loading.tsx~Loading',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx~ContextualSaveBar',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/DiscardConfirmationModal.tsx~DiscardConfirmationModal',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/DiscardConfirmationModal.tsx~DiscardConfirmationModalProps',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/CSSAnimation/CSSAnimation.tsx~CSSAnimation',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/CSSAnimation/CSSAnimation.tsx~CSSAnimationProps',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/FormLayout.tsx~FormLayoutProps',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/FormLayout.tsx~FormLayout',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Item/Item.tsx~ItemProps',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Group/Group.tsx~Group',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Group/Group.tsx~GroupProps',
    '/Users/foo/polaris/polaris-react/src/components/Form/Form.tsx~Form',
    '/Users/foo/polaris/polaris-react/src/components/Form/Form.tsx~FormProps',
    '/Users/foo/polaris/polaris-react/src/components/FooterHelp/FooterHelp.tsx~FooterHelp',
    '/Users/foo/polaris/polaris-react/src/components/FooterHelp/FooterHelp.tsx~FooterHelpProps',
    '/Users/foo/polaris/polaris-react/src/components/FocusManager/FocusManager.tsx~FocusManager',
    '/Users/foo/polaris/polaris-react/src/components/Focus/Focus.tsx~FocusProps',
    '/Users/foo/polaris/polaris-react/src/components/Focus/Focus.tsx~Focus',
    '/Users/foo/polaris/polaris-react/src/components/Filters/Filters.tsx~Filters',
    '/Users/foo/polaris/polaris-react/src/components/Filters/Filters.tsx~FiltersProps',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/SearchField/SearchField.tsx~SearchField',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/SearchField/SearchField.tsx~SearchFieldProps',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FiltersBar/FiltersBar.tsx~FiltersBar',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FiltersBar/FiltersBar.tsx~FiltersBarProps',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx~FilterPill',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx~FilterPillProps',
    '/Users/foo/polaris/polaris-react/src/components/FilterActionsProvider/FilterActionsProvider.tsx~FilterActionsProvider',
    '/Users/foo/polaris/polaris-react/src/components/FilterActionsProvider/FilterActionsProvider.tsx~FilterActionsContext',
    '/Users/foo/polaris/polaris-react/src/components/ExceptionList/ExceptionList.tsx~ExceptionList',
    '/Users/foo/polaris/polaris-react/src/components/ExceptionList/ExceptionList.tsx~ExceptionListProps',
    '/Users/foo/polaris/polaris-react/src/components/EventListener/EventListener.tsx~EventListenerProps',
    '/Users/foo/polaris/polaris-react/src/components/EventListener/EventListener.tsx~EventListener',
    '/Users/foo/polaris/polaris-react/src/components/EphemeralPresenceManager/EphemeralPresenceManager.tsx~EphemeralPresenceManager',
    '/Users/foo/polaris/polaris-react/src/components/EphemeralPresenceManager/EphemeralPresenceManager.tsx~EphemeralPresenceManagerProps',
    '/Users/foo/polaris/polaris-react/src/components/EmptyState/EmptyState.tsx~EmptyState',
    '/Users/foo/polaris/polaris-react/src/components/EmptyState/EmptyState.tsx~EmptyStateProps',
    '/Users/foo/polaris/polaris-react/src/components/EmptySearchResult/EmptySearchResult.tsx~EmptySearchResult',
    '/Users/foo/polaris/polaris-react/src/components/EmptySearchResult/EmptySearchResult.tsx~EmptySearchResultProps',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/context.tsx~DropZoneContext',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/DropZone.tsx~DropZoneFileType',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/DropZone.tsx~DropZoneProps',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/DropZone.tsx~DropZone',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/components/FileUpload/FileUpload.tsx~FileUpload',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/components/FileUpload/FileUpload.tsx~FileUploadProps',
    '/Users/foo/polaris/polaris-react/src/components/Divider/Divider.tsx~DividerProps',
    '/Users/foo/polaris/polaris-react/src/components/Divider/Divider.tsx~Divider',
    '/Users/foo/polaris/polaris-react/src/components/DescriptionList/DescriptionList.tsx~DescriptionList',
    '/Users/foo/polaris/polaris-react/src/components/DescriptionList/DescriptionList.tsx~DescriptionListProps',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/utilities.tsx~monthName',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/utilities.tsx~weekdayName',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/DatePicker.tsx~DatePicker',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/DatePicker.tsx~Range',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/DatePicker.tsx~DatePickerProps',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Weekday/Weekday.tsx~WeekdayProps',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Weekday/Weekday.tsx~Weekday',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Month/Month.tsx~Month',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Month/Month.tsx~MonthProps',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Day/Day.tsx~DayProps',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Day/Day.tsx~Day',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~DataTable',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~SortDirection',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~TableRow',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~TableData',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~ColumnContentType',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~DataTablePaginationProps',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~DataTableProps',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Navigation/Navigation.tsx~Navigation',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Navigation/Navigation.tsx~NavigationProps',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Cell/Cell.tsx~Cell',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Cell/Cell.tsx~CellProps',
    '/Users/foo/polaris/polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.tsx~ContextualSaveBarProps',
    '/Users/foo/polaris/polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.tsx~ContextualSaveBar',
    '/Users/foo/polaris/polaris-react/src/components/Connected/Connected.tsx~Connected',
    '/Users/foo/polaris/polaris-react/src/components/Connected/Connected.tsx~ConnectedProps',
    '/Users/foo/polaris/polaris-react/src/components/Connected/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/Connected/components/Item/Item.tsx~ItemProps',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/Combobox.tsx~Combobox',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/Combobox.tsx~ComboboxProps',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/components/TextField/TextField.tsx~TextField',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/ColorPicker.tsx~ColorPickerProps',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/ColorPicker.tsx~ColorPicker',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/Slidable/Slidable.tsx~SlidableProps',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/Slidable/Slidable.tsx~Slidable',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/HuePicker/HuePicker.tsx~HuePickerProps',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/HuePicker/HuePicker.tsx~HuePicker',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/AlphaPicker/AlphaPicker.tsx~AlphaPickerProps',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/AlphaPicker/AlphaPicker.tsx~AlphaPicker',
    '/Users/foo/polaris/polaris-react/src/components/Collapsible/Collapsible.tsx~Collapsible',
    '/Users/foo/polaris/polaris-react/src/components/Collapsible/Collapsible.tsx~CollapsibleProps',
    '/Users/foo/polaris/polaris-react/src/components/ChoiceList/ChoiceList.tsx~ChoiceList',
    '/Users/foo/polaris/polaris-react/src/components/ChoiceList/ChoiceList.tsx~ChoiceListProps',
    '/Users/foo/polaris/polaris-react/src/components/Choice/Choice.tsx~Choice',
    '/Users/foo/polaris/polaris-react/src/components/Choice/Choice.tsx~helpTextID',
    '/Users/foo/polaris/polaris-react/src/components/Choice/Choice.tsx~ChoiceBleedProps',
    '/Users/foo/polaris/polaris-react/src/components/Checkbox/Checkbox.tsx~CheckboxProps',
    '/Users/foo/polaris/polaris-react/src/components/Checkbox/Checkbox.tsx~Checkbox',
    '/Users/foo/polaris/polaris-react/src/components/CheckableButton/CheckableButton.tsx~CheckableButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/CheckableButton/CheckableButton.tsx~CheckableButton',
    '/Users/foo/polaris/polaris-react/src/components/Card/Card.tsx~CardProps',
    '/Users/foo/polaris/polaris-react/src/components/Card/Card.tsx~Card',
    '/Users/foo/polaris/polaris-react/src/components/CalloutCard/CalloutCard.tsx~CalloutCard',
    '/Users/foo/polaris/polaris-react/src/components/CalloutCard/CalloutCard.tsx~CalloutCardProps',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/ButtonGroup.tsx~ButtonGroup',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/ButtonGroup.tsx~ButtonGroupProps',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/components/Item/Item.tsx~ItemProps',
    '/Users/foo/polaris/polaris-react/src/components/Button/utils.tsx~buttonsFrom',
    '/Users/foo/polaris/polaris-react/src/components/Button/utils.tsx~buttonFrom',
    '/Users/foo/polaris/polaris-react/src/components/Button/Button.tsx~Button',
    '/Users/foo/polaris/polaris-react/src/components/Button/Button.tsx~ButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/BulkActions.tsx~BulkActions',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/BulkActions.tsx~BulkAction',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/BulkActions.tsx~BulkActionsProps',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionMenu/index.tsx~BulkActionMenu',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionMenu/index.tsx~BulkActionsMenuProps',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionMenu/BulkActionMenu.tsx~BulkActionMenu',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionMenu/BulkActionMenu.tsx~BulkActionsMenuProps',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx~BulkActionButton',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx~BulkActionButtonProps',
    '/Users/foo/polaris/polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx~Breadcrumbs',
    '/Users/foo/polaris/polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx~BreadcrumbsProps',
    '/Users/foo/polaris/polaris-react/src/components/Box/Box.tsx~Element',
    '/Users/foo/polaris/polaris-react/src/components/Box/Box.tsx~BoxProps',
    '/Users/foo/polaris/polaris-react/src/components/Box/Box.tsx~Box',
    '/Users/foo/polaris/polaris-react/src/components/BlockStack/BlockStack.tsx~BlockStackProps',
    '/Users/foo/polaris/polaris-react/src/components/BlockStack/BlockStack.tsx~BlockStack',
    '/Users/foo/polaris/polaris-react/src/components/Bleed/Bleed.tsx~BleedProps',
    '/Users/foo/polaris/polaris-react/src/components/Bleed/Bleed.tsx~Bleed',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~BannerLayout',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~DefaultBanner',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~InlineIconBanner',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~WithinContentContainerBanner',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~BannerTone',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~BannerProps',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~Banner',
    '/Users/foo/polaris/polaris-react/src/components/Badge/Badge.tsx~Badge',
    '/Users/foo/polaris/polaris-react/src/components/Badge/Badge.tsx~BadgeProps',
    '/Users/foo/polaris/polaris-react/src/components/Badge/components/Pip/Pip.tsx~Pip',
    '/Users/foo/polaris/polaris-react/src/components/Badge/components/Pip/Pip.tsx~PipProps',
    '/Users/foo/polaris/polaris-react/src/components/Backdrop/Backdrop.tsx~Backdrop',
    '/Users/foo/polaris/polaris-react/src/components/Backdrop/Backdrop.tsx~BackdropProps',
    '/Users/foo/polaris/polaris-react/src/components/Avatar/Avatar.tsx~Avatar',
    '/Users/foo/polaris/polaris-react/src/components/Avatar/Avatar.tsx~STYLE_CLASSES',
    '/Users/foo/polaris/polaris-react/src/components/Avatar/Avatar.tsx~AvatarProps',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/Autocomplete.tsx~AutocompleteProps',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/Autocomplete.tsx~Autocomplete',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/components/MappedOption/MappedOption.tsx~MappedOption',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/components/MappedAction/MappedAction.tsx~MappedAction',
    '/Users/foo/polaris/polaris-react/src/components/AppProvider/AppProvider.tsx~AppProviderProps',
    '/Users/foo/polaris/polaris-react/src/components/AppProvider/AppProvider.tsx~AppProvider',
    '/Users/foo/polaris/polaris-react/src/components/AfterInitialMount/AfterInitialMount.tsx~AfterInitialMount',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/ActionMenu.tsx~ActionMenu',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/ActionMenu.tsx~hasGroupsWithActions',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/ActionMenu.tsx~ActionMenuProps',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx~SecondaryAction',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.tsx~RollupActions',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.tsx~RollupActionsProps',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx~MenuGroup',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx~MenuGroupProps',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/Actions/Actions.tsx~Actions',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/ActionList.tsx~ActionList',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/ActionList.tsx~ActionListProps',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/ActionList.tsx~ActionListItemProps',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Section/Section.tsx~Section',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Section/Section.tsx~SectionProps',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Item/Item.tsx~Item',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Item/Item.tsx~ItemProps',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Item/Item.tsx~TruncateText',
    '/Users/foo/polaris/polaris-react/src/components/AccountConnection/AccountConnection.tsx~AccountConnection',
    '/Users/foo/polaris/polaris-react/src/components/AccountConnection/AccountConnection.tsx~AccountConnectionProps',
  ],
  perfectResult: {
    // Duplicate component names. Would need parent layers/pages to differentiate
    '109103:28058' /* Spinner */:
      '/Users/foo/polaris/polaris-react/src/components/Spinner/Spinner.tsx~Spinner',
    '108224:8280' /* Section */:
      '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Section/Section.tsx~Section',
    '111606:72844' /* Option */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Option/Option.tsx~Option',
    '111636:2455' /* Cell */:
      '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Cell/Cell.tsx~Cell',
    '109785:19497' /* Search field */:
      '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchField/SearchField.tsx~SearchField',
    '108458:10011' /* Contextual save bar */:
      '/Users/foo/polaris/polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.tsx~ContextualSaveBar',
    '108407:11851' /* Text field */:
      '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.tsx~TextField',
    '108368:1341' /* Checkbox */:
      '/Users/foo/polaris/polaris-react/src/components/Checkbox/Checkbox.tsx~Checkbox',

    // Duplicate component name in same layer
    '108797:54548' /* Day */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Day/Day.tsx~Day',

    // Non-matching component names. Would need parent layers/pages identify
    '108943:4401' /* Title bar */:
      '/Users/foo/polaris/polaris-react/src/components/Modal/components/Header/Header.tsx~Header',

    // Typo in component name / not an exact match
    '111674:1339' /* Lisbox */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.tsx~Listbox',
    '110912:43515' /* Index filter */:
      '/Users/foo/polaris/polaris-react/src/components/IndexFilters/IndexFilters.tsx~IndexFilters',

    // simple matches
    '109630:31250' /* Video thumbnail */:
      '/Users/foo/polaris/polaris-react/src/components/VideoThumbnail/VideoThumbnail.tsx~VideoThumbnail',
    '109785:19170' /* Top bar */:
      '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.tsx~TopBar',
    '109785:19481' /* User menu */:
      '/Users/foo/polaris/polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx~UserMenu',
    '110065:49636' /* Tooltip */:
      '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx~Tooltip',
    '108524:15659' /* Toast */:
      '/Users/foo/polaris/polaris-react/src/components/Toast/Toast.tsx~Toast',
    '109135:42783' /* Thumbnail */:
      '/Users/foo/polaris/polaris-react/src/components/Thumbnail/Thumbnail.tsx~Thumbnail',
    '109012:41728' /* Tag */: '/Users/foo/polaris/polaris-react/src/components/Tag/Tag.tsx~Tag',
    '110386:1423' /* Tabs */: '/Users/foo/polaris/polaris-react/src/components/Tabs/Tabs.tsx~Tabs',
    '110371:90046' /* Tab */:
      '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/Tab.tsx~Tab',
    '62007:21648' /* Skeleton thumbnail */:
      '/Users/foo/polaris/polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx~SkeletonThumbnail',
    '62007:21531' /* Skeleton display text */:
      '/Users/foo/polaris/polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.tsx~SkeletonDisplayText',
    '62007:21609' /* Skeleton body text */:
      '/Users/foo/polaris/polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.tsx~SkeletonBodyText',
    '108526:14477' /* Select */:
      '/Users/foo/polaris/polaris-react/src/components/Select/Select.tsx~Select',
    '110491:47135' /* Resource list */:
      '/Users/foo/polaris/polaris-react/src/components/ResourceList/ResourceList.tsx~ResourceList',
    '53359:25889' /* .Resource Item */:
      '/Users/foo/polaris/polaris-react/src/components/ResourceItem/ResourceItem.tsx~ResourceItem',
    '109643:22164' /* Range slider */:
      '/Users/foo/polaris/polaris-react/src/components/RangeSlider/RangeSlider.tsx~RangeSlider',
    '108368:2270' /* Radio button */:
      '/Users/foo/polaris/polaris-react/src/components/RadioButton/RadioButton.tsx~RadioButton',
    '27579:4563' /* Progress bar */:
      '/Users/foo/polaris/polaris-react/src/components/ProgressBar/ProgressBar.tsx~ProgressBar',
    '110421:9260' /* Popover */:
      '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx~Popover',
    '108807:10772' /* Pagination */:
      '/Users/foo/polaris/polaris-react/src/components/Pagination/Pagination.tsx~Pagination',
    '108807:15671' /* Page actions */:
      '/Users/foo/polaris/polaris-react/src/components/PageActions/PageActions.tsx~PageActions',
    '111691:69452' /* Page */: '/Users/foo/polaris/polaris-react/src/components/Page/Page.tsx~Page',
    '111691:53161' /* Header */:
      '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/Header.tsx~Header',
    '109368:18066' /* Option list */:
      '/Users/foo/polaris/polaris-react/src/components/OptionList/OptionList.tsx~OptionList',
    '109776:121231' /* Navigation */:
      '/Users/foo/polaris/polaris-react/src/components/Navigation/Navigation.tsx~Navigation',
    '111368:23985' /* Modal */:
      '/Users/foo/polaris/polaris-react/src/components/Modal/Modal.tsx~Modal',
    '108974:9575' /* Footer */:
      '/Users/foo/polaris/polaris-react/src/components/Modal/components/Footer/Footer.tsx~Footer',
    '109745:85696' /* Media card */:
      '/Users/foo/polaris/polaris-react/src/components/MediaCard/MediaCard.tsx~MediaCard',
    '111674:30439' /* Header */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Header/Header.tsx~Header',
    '111596:71602' /* Action */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Action/Action.tsx~Action',
    '108808:30098' /* Link */: '/Users/foo/polaris/polaris-react/src/components/Link/Link.tsx~Link',
    '86562:46659' /* .Tabs legacy */:
      '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/LegacyTabs.tsx~LegacyTabs',

    '78394:31942' /* .Layout */:
      '/Users/foo/polaris/polaris-react/src/components/Layout/Layout.tsx~Layout',
    '28210:12203' /* Inline error */:
      '/Users/foo/polaris/polaris-react/src/components/InlineError/InlineError.tsx~InlineError',
    '109557:3763' /* Indicator */:
      '/Users/foo/polaris/polaris-react/src/components/Indicator/Indicator.tsx~Indicator',
    '111680:45555' /* Index table */:
      '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx~IndexTable',
    '56963:30933' /* .Grid */: '/Users/foo/polaris/polaris-react/src/components/Grid/Grid.tsx~Grid',
    '110000:10540' /* Fullscreen bar */:
      '/Users/foo/polaris/polaris-react/src/components/FullscreenBar/FullscreenBar.tsx~FullscreenBar',
    '108808:30394' /* Footer help */:
      '/Users/foo/polaris/polaris-react/src/components/FooterHelp/FooterHelp.tsx~FooterHelp',
    '111407:92131' /* Filters */:
      '/Users/foo/polaris/polaris-react/src/components/Filters/Filters.tsx~Filters',
    '111562:48065' /* Filters bar */:
      '/Users/foo/polaris/polaris-react/src/components/Filters/components/FiltersBar/FiltersBar.tsx~FiltersBar',
    '111058:33366' /* Filter pill */:
      '/Users/foo/polaris/polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx~FilterPill',
    '108933:30513' /* Exception list */:
      '/Users/foo/polaris/polaris-react/src/components/ExceptionList/ExceptionList.tsx~ExceptionList',
    '109979:8183' /* Empty state */:
      '/Users/foo/polaris/polaris-react/src/components/EmptyState/EmptyState.tsx~EmptyState',
    '109178:44479' /* Drop zone */:
      '/Users/foo/polaris/polaris-react/src/components/DropZone/DropZone.tsx~DropZone',
    '109745:84282' /* Divider */:
      '/Users/foo/polaris/polaris-react/src/components/Divider/Divider.tsx~Divider',
    '109630:30271' /* Description list */:
      '/Users/foo/polaris/polaris-react/src/components/DescriptionList/DescriptionList.tsx~DescriptionList',
    '108914:2585' /* DatePicker */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/DatePicker.tsx~DatePicker',
    '108797:52864' /* Day of week */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Weekday/Weekday.tsx~Weekday',
    '108797:52863' /* Month */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Month/Month.tsx~Month',
    '111636:2477' /* Data table */:
      '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx~DataTable',
    '111683:62772' /* Navigation */:
      '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Navigation/Navigation.tsx~Navigation',
    '108433:7829' /* Color picker */:
      '/Users/foo/polaris/polaris-react/src/components/ColorPicker/ColorPicker.tsx~ColorPicker',
    '109134:7785' /* Choice list */:
      '/Users/foo/polaris/polaris-react/src/components/ChoiceList/ChoiceList.tsx~ChoiceList',
    '109372:20170' /* Card */: '/Users/foo/polaris/polaris-react/src/components/Card/Card.tsx~Card',
    '109313:7455' /* Callout card */:
      '/Users/foo/polaris/polaris-react/src/components/CalloutCard/CalloutCard.tsx~CalloutCard',
    '108782:4042' /* ButtonGroup */:
      '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/ButtonGroup.tsx~ButtonGroup',
    '108641:35692' /* Button */:
      '/Users/foo/polaris/polaris-react/src/components/Button/Button.tsx~Button',
    '110641:64122' /* Bulk actions */:
      '/Users/foo/polaris/polaris-react/src/components/BulkActions/BulkActions.tsx~BulkActions',
    '109293:4284' /* Banner */:
      '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx~Banner',
    '108227:921' /* Badge */:
      '/Users/foo/polaris/polaris-react/src/components/Badge/Badge.tsx~Badge',
    '107957:44068' /* Avatar */:
      '/Users/foo/polaris/polaris-react/src/components/Avatar/Avatar.tsx~Avatar',
    '110065:29772' /* Secondary action */:
      '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx~SecondaryAction',
    '108977:15501' /* Action List */:
      '/Users/foo/polaris/polaris-react/src/components/ActionList/ActionList.tsx~ActionList',
    '109630:23132' /* Account Connection */:
      '/Users/foo/polaris/polaris-react/src/components/AccountConnection/AccountConnection.tsx~AccountConnection',
  },
}

export default polarisReact
