import { AutolinkingTestCase } from '../types'

const polarisReact: AutolinkingTestCase = {
  name: 'Polaris - react',
  passThreshold: 0.75, // most remaining failures due to lacking context
  figmaComponents: [
    { name: '.Mobile top bar', id: '111471:102036' },
    { name: '.slot examples', id: '111368:28722' },
    { name: '.domains-empty-state', id: '111320:34097' },
    { name: '.Screenshots', id: '111176:10398' },
    { name: '.Subcomponent header', id: '110918:22796' },
    { name: '.Component header', id: '110918:17606' },
    { name: '.Variant Detail', id: '107969:44241' },
    { name: '.Variant Title', id: '107969:44237' },
    { name: '.Spec header', id: '107969:44234' },
    { name: 'UI Shell', id: '111726:87471' },
    { name: 'Mobile device', id: '111471:101064' },
    { name: 'Country', id: '111377:33185' },
    { name: 'Slot', id: '108511:12346' },
    { name: 'Cursor', id: '84608:38801' },
    { name: 'Product image', id: '107922:1712' },
    { name: '.Grid', id: '56963:30933' },
    { name: '.Card', id: '84164:61609' },
    { name: '.Assets/Row', id: '84164:61469' },
    { name: '.Assets/Header', id: '84164:61450' },
    { name: '.Filters', id: '27668:11096' },
    { name: '.Layout', id: '78394:31942' },
    { name: '.Setting toggle', id: '77196:32435' },
    { name: '.Tabs legacy', id: '86562:46659' },
    { name: '.Assets/Tab legacy', id: '86562:46430' },
    { name: 'Video thumbnail', id: '109630:31250' },
    { name: 'Play button', id: '109630:31207' },
    { name: '.Play button', id: '67330:21527' },
    { name: '.Video thumbnail', id: '50769:21077' },
    { name: 'Top bar', id: '109785:19170' },
    { name: 'Sidekick', id: '109785:19597' },
    { name: 'Secondary menu', id: '109785:19581' },
    { name: 'Right content', id: '111489:106090' },
    { name: 'Logo', id: '109785:19525' },
    { name: 'Search field', id: '109785:19497' },
    { name: 'User menu', id: '109785:19481' },
    { name: 'Nav toggle', id: '111489:106398' },
    { name: '.Assets / Sidekick button', id: '81750:31329' },
    { name: '.Assets / Alerts button', id: '81750:31068' },
    { name: '.Top bar', id: '28822:336' },
    { name: '.Assets/Logo', id: '112354:366' },
    { name: '.Assets/Store switcher', id: '29236:14848' },
    { name: '.Assets/Search field', id: '28822:175' },
    { name: '.Assets/Store menu button', id: '28822:309' },
    { name: '.Assets/Nav toggle', id: '463:3086' },
    { name: 'Tooltip', id: '110065:49636' },
    { name: '.Assets/Tail', id: '109814:45727' },
    { name: '.Tooltip', id: '109814:45676' },
    { name: 'Toast', id: '108524:15659' },
    { name: '.Toast', id: '29653:21166' },
    { name: 'Thumbnail', id: '109135:42783' },
    { name: '.Thumbnail', id: '27579:4928' },
    { name: 'Text field', id: '108407:11851' },
    { name: 'Segment bottom', id: '108462:8505' },
    { name: 'Segment top', id: '108462:8360' },
    { name: 'Stepper', id: '108462:8487' },
    { name: 'Suffix', id: '108407:11452' },
    { name: 'Prefix', id: '108407:11457' },
    { name: 'Multiline field', id: '108420:1346' },
    { name: 'Number field', id: '108462:8059' },
    { name: '.text field', id: '29426:139' },
    { name: '.number field', id: '52267:23042' },
    { name: '.multiline text field', id: '52267:23224' },
    { name: '.assets/Prefix', id: '51903:22671' },
    { name: '.assets/Suffix', id: '51903:22664' },
    { name: '.assets/Stepper', id: '28915:15180' },
    { name: '.assets/Input', id: '28915:15501' },
    { name: 'Tag', id: '109012:41728' },
    { name: 'Remove button', id: '108973:33251' },
    { name: '.Tag', id: '27579:4688' },
    { name: '.Removable tag', id: '51536:23822' },
    { name: '.Clickable tag', id: '51536:23867' },
    { name: 'Tabs', id: '110386:1423' },
    { name: 'Tab', id: '110371:90046' },
    { name: 'Disclosure tab', id: '110371:91554' },
    { name: 'Icon only', id: '110371:90077' },
    { name: 'Mobile/Tabs', id: '110386:1832' },
    { name: 'Tab', id: '110386:1794' },
    { name: 'Disclosure tab', id: '110386:1778' },
    { name: 'Icon only', id: '110386:1771' },
    { name: '.Tabs', id: '84001:38965' },
    { name: '.Assets/Tab', id: '84001:38745' },
    { name: 'Spinner', id: '109103:28058' },
    { name: 'Animation', id: '109103:27976' },
    { name: '.Spinner', id: '27579:4687' },
    { name: 'Skeleton thumbnail', id: '62007:21648' },
    { name: 'Skeleton display text', id: '62007:21531' },
    { name: 'Skeleton body text', id: '62007:21609' },
    { name: 'Select', id: '108526:14477' },
    { name: 'Input text', id: '108611:1968' },
    { name: '.select', id: '29402:14771' },
    { name: '.assets/Help text/Default', id: '51521:23138' },
    { name: '.assets/Select field', id: '29281:14870' },
    { name: 'Resource list', id: '110491:47135' },
    { name: 'Resource header', id: '110491:46855' },
    { name: 'Item with shortcut action', id: '110491:50540' },
    { name: 'Item', id: '110491:36572' },
    { name: 'Mobile/Resource list', id: '111025:10258' },
    { name: 'Item', id: '110944:6122' },
    { name: '.Resource list', id: '53484:22500' },
    { name: '.Assets/Header', id: '53457:26770' },
    { name: '.Resource Item', id: '53359:25889' },
    { name: 'Range slider', id: '109643:22164' },
    { name: 'Thumb', id: '109304:4612' },
    { name: '.Range slider', id: '28915:14403' },
    { name: '.Assets/Slider', id: '51161:21809' },
    { name: '.Assets/Thumb', id: '28915:14395' },
    { name: 'Radio button', id: '108368:2270' },
    { name: '.assets/Help text', id: '50733:21486' },
    { name: '.radio button with label', id: '27648:7547' },
    { name: '.radio button', id: '27648:7332' },
    { name: 'Progress bar', id: '27579:4563' },
    { name: 'Popover', id: '110421:9260' },
    { name: '.Popover', id: '29461:2488' },
    { name: 'Pagination', id: '108807:10772' },
    { name: 'Next button', id: '109134:14508' },
    { name: 'Previous button', id: '108807:10757' },
    { name: '.Pagination', id: '29604:275' },
    { name: '.Assets/Pagination', id: '27579:4558' },
    { name: 'Page actions', id: '108807:15671' },
    { name: '.Page actions', id: '27579:4555' },
    { name: 'Page', id: '111691:69452' },
    { name: 'Header', id: '111691:53161' },
    { name: 'Actions', id: '111691:49869' },
    { name: 'Secondary action', id: '110065:29772' },
    { name: '.Page', id: '29461:862' },
    { name: '.Apps', id: '50358:21280' },
    { name: '.Marketing', id: '50358:21192' },
    { name: '.Analytics', id: '50343:22256' },
    { name: '.Finances', id: '50343:21983' },
    { name: '.Customers', id: '50294:21556' },
    { name: '.Products', id: '50267:23178' },
    { name: '.Orders', id: '50257:20692' },
    { name: '.Assets/Picker', id: '105937:3862' },
    { name: '.Assets/Secondary action', id: '29461:405' },
    { name: '.Assets/Actions', id: '50175:20678' },
    { name: 'Option list', id: '109368:18066' },
    { name: 'Option item', id: '109368:18196' },
    { name: '.Option list', id: '29413:20540' },
    { name: '.Assets/Option item', id: '29413:20275' },
    { name: 'Navigation', id: '109776:121231' },
    { name: 'Mobile/Navigation', id: '110015:22901' },
    { name: 'Section title', id: '109776:59846' },
    { name: 'Indicator', id: '109557:3763' },
    { name: 'Child item', id: '109776:99624' },
    { name: 'Parent item', id: '109776:99486' },
    { name: 'Home', id: '110015:21471' },
    { name: 'Discounts', id: '110015:22199' },
    { name: 'Shop', id: '110015:22463' },
    { name: 'Settings', id: '110015:21387' },
    { name: 'Email', id: '109834:130935' },
    { name: 'Point of sale', id: '109834:128562' },
    { name: 'Online store', id: '109834:128450' },
    { name: 'Marketing', id: '109821:122273' },
    { name: 'Analytics', id: '109821:122187' },
    { name: 'Finances', id: '109821:121519' },
    { name: 'Content', id: '109821:121434' },
    { name: 'Customers', id: '109776:119185' },
    { name: 'Products', id: '109821:121349' },
    { name: 'Orders', id: '109776:119162' },
    { name: '.Mobile/Subcomponents/Section title', id: '110015:19647' },
    { name: '.Mobile/Subcomponents/Child item', id: '110015:19623' },
    { name: '.Mobile/Subcomponents/Parent item', id: '110015:19563' },
    { name: '.Assets/Section title', id: '68778:30923' },
    { name: '.Navigation', id: '29410:38339' },
    { name: '.Assets/Items', id: '29402:14828' },
    { name: 'Modal', id: '111368:23985' },
    { name: 'Footer', id: '108974:9575' },
    { name: 'Title bar', id: '108943:4401' },
    { name: '.Assets/Header', id: '31716:59' },
    { name: '.Modal', id: '28348:17068' },
    { name: 'Media card', id: '109745:85696' },
    { name: '.Media card', id: '27579:3745' },
    { name: 'Lisbox', id: '111674:1339' },
    { name: 'Option', id: '111606:72844' },
    { name: 'Action', id: '111596:71602' },
    { name: 'Header', id: '111674:30439' },
    { name: 'Link', id: '108808:30098' },
    { name: '.Link', id: '51555:21010' },
    { name: 'Keyboard key', id: '110000:10862' },
    { name: '.Keyboard key', id: '84172:42079' },
    { name: 'Inline error', id: '28210:12203' },
    { name: 'Index table', id: '111680:45555' },
    { name: 'Mobile/Index table', id: '111720:37938' },
    { name: '.Mobile/Subcomponents/Row', id: '111720:36964' },
    { name: 'Footer', id: '111720:38284' },
    { name: 'Selection count row', id: '111612:75208' },
    { name: 'Horizontal scroll bar', id: '110641:62520' },
    { name: 'Bulk actions', id: '110641:64122' },
    { name: 'Sort icon', id: '110421:26662' },
    { name: 'Column reorder', id: '111612:64433' },
    { name: 'Column', id: '110421:25965' },
    { name: 'Index cell', id: '110421:25820' },
    { name: 'Index header cell', id: '110421:25812' },
    { name: '.Filter pill', id: '110912:39848' },
    { name: '.Filter pill', id: '68605:33198' },
    { name: '.Assets / Column reorder', id: '68412:37925' },
    { name: '.Assets/Bulk actions', id: '67296:23823' },
    { name: '.Assets/Sort icon', id: '67238:23155' },
    { name: '.Index filtering', id: '110421:26501' },
    { name: '.Index filtering', id: '67128:21676' },
    { name: '.Index table', id: '45017:32955' },
    { name: '.Assets/Column', id: '44707:19605' },
    { name: '.Assets/Cell/Table cell', id: '44707:19591' },
    { name: '.Assets/Cell/Header cell', id: '44707:19586' },
    { name: '.Assets/Small screen row', id: '45051:22536' },
    { name: 'Index filter', id: '110912:43515' },
    { name: 'Mobile/Index filter', id: '111358:31613' },
    { name: '.Mobile/Subcomponents/Controls', id: '111187:36083' },
    { name: 'Controls', id: '111028:39573' },
    { name: 'Footer help', id: '108808:30394' },
    { name: '.Footer help', id: '27579:4554' },
    { name: 'Fullscreen bar', id: '110000:10540' },
    { name: '.Fullscreem bar', id: '71205:18753' },
    { name: 'Filters', id: '111407:92131' },
    { name: 'Mobile/Filters', id: '111720:35800' },
    { name: 'Filters Bar', id: '111562:48065' },
    { name: 'Filter pill', id: '111058:33366' },
    { name: 'Add filter', id: '111058:33314' },
    { name: '.Filter pill', id: '110421:26830' },
    { name: 'Exception list', id: '108933:30513' },
    { name: '.Exception list', id: '27579:4537' },
    { name: 'Empty state', id: '109979:8183' },
    { name: 'Illustration', id: '111306:33428' },
    { name: '.Assets/Spot Illustration', id: '12979:10119' },
    { name: '.Assets/Illustration', id: '49495:19719' },
    { name: '.Empty state', id: '27579:4461' },
    { name: 'Drop zone', id: '109178:44479' },
    { name: '.Drop zone', id: '27579:4342' },
    { name: 'Divider', id: '109745:84282' },
    { name: '.Divider', id: '73002:33613' },
    { name: 'Description list', id: '109630:30271' },
    { name: 'List item', id: '109630:30179' },
    { name: '.Description list', id: '53638:30530' },
    { name: '.Assets/List item', id: '53638:30483' },
    { name: 'DatePicker', id: '108914:2585' },
    { name: 'Month', id: '108797:52863' },
    { name: 'Day of week', id: '108797:52864' },
    { name: 'Day', id: '108797:54548' },
    { name: 'Day', id: '108797:52832' },
    { name: 'Range calendar', id: '108797:55823' },
    { name: 'Base calendar', id: '108797:55720' },
    { name: '.Assets/Month', id: '68742:21620' },
    { name: '.Assets/Day of week', id: '51054:21537' },
    { name: '.Assets/Date', id: '51054:21522' },
    { name: '.Date picker', id: '27668:11405' },
    { name: 'Data table', id: '111636:2477' },
    { name: 'Mobile/Data table', id: '111683:79795' },
    { name: 'Footer', id: '111683:63838' },
    { name: 'Navigation', id: '111683:62772' },
    { name: 'Column', id: '111636:2490' },
    { name: 'Cell', id: '111636:2455' },
    { name: 'Totals', id: '111636:2430' },
    { name: 'Heading', id: '111636:2394' },
    { name: '.Assets/Table footer', id: '8307:12310' },
    { name: '.Assets/Table row', id: '53538:27024' },
    { name: '.Assets/Header/Cell', id: '53538:25532' },
    { name: '.Assets/Table header', id: '53538:25524' },
    { name: '.Data table', id: '27800:2137' },
    { name: '.Assets/Mobile only/Navigation', id: '8392:16389' },
    { name: '.Assets/Totals row', id: '27668:13612' },
    { name: 'Contextual save bar', id: '108458:10011' },
    { name: '.Contextual save bar', id: '27579:4250' },
    { name: 'Color picker', id: '108433:7829' },
    { name: '.Color picker', id: '27579:730' },
    { name: 'Choice list', id: '109134:7785' },
    { name: '.choice list', id: '28210:21889' },
    { name: 'Checkbox', id: '108368:1341' },
    { name: '.assets/Help text', id: '50716:21060' },
    { name: '.checkbox with label', id: '27579:515' },
    { name: '.Checkbox', id: '27579:728' },
    { name: 'Card', id: '109372:20170' },
    { name: '.Assets/Section title', id: '105343:2566' },
    { name: '.Assets/Card title', id: '94021:80366' },
    { name: '.Card examples', id: '75727:32170' },
    { name: '.Card alpha', id: '75727:32130' },
    { name: 'Callout card', id: '109313:7455' },
    { name: 'Illustration', id: '111176:4158' },
    { name: '.Assets', id: '93027:59250' },
    { name: '.Callout card', id: '84164:64397' },
    { name: '.Assets/Illustration', id: '49245:19864' },
    { name: 'Button group segmented', id: '109118:3325' },
    { name: 'Button group', id: '108782:4042' },
    { name: '.Button group', id: '27566:7963' },
    { name: 'Button', id: '108641:35692' },
    { name: 'Icon button', id: '108666:39153' },
    { name: '.button-shine', id: '108666:37138' },
    { name: '.Default button', id: '53964:22768' },
    { name: '.Primary button', id: '53964:22769' },
    { name: '.Tertiary button', id: '53971:23149' },
    { name: '.Tertiary critical button', id: '83656:36193' },
    { name: '.Critical button', id: '83656:36204' },
    { name: '.Plain button', id: '83637:53940' },
    { name: '.Plain critical button', id: '84120:42002' },
    { name: '.Plain monochrome', id: '84129:49491' },
    { name: '.Primary critical button', id: '53964:22800' },
    { name: '.Primary success button', id: '83621:48297' },
    { name: '.Icon button', id: '84375:42685' },
    { name: '.Split button', id: '97516:71658' },
    { name: 'Banner', id: '109293:4284' },
    { name: '.Banner', id: '83621:42265' },
    { name: '.Banner with no title', id: '85796:58679' },
    { name: 'Badge', id: '108227:921' },
    { name: 'Progress Indicator', id: '108227:892' },
    { name: '.Badge', id: '26521:97' },
    { name: '.Assets/Progress', id: '26521:136' },
    { name: 'Avatar', id: '107957:44068' },
    { name: '.Avatar + label', id: '87434:46985' },
    { name: '.avatar', id: '87434:46824' },
    { name: 'Action List', id: '108977:15501' },
    { name: 'Section', id: '108224:8280' },
    { name: 'Destructive item', id: '108180:1430' },
    { name: 'Item', id: '108154:1050' },
    { name: '.Action list', id: '29413:20122' },
    { name: '.Assets/Items', id: '26376:6454' },
    { name: 'Account Connection', id: '109630:23132' },
    { name: '.Account connection', id: '26497:388' },
  ],
  componentPaths: [
    '/Users/foo/polaris/polaris-react/tests/utilities/react-testing.tsx',
    '/Users/foo/polaris/polaris-react/tests/utilities/listbox.tsx',
    '/Users/foo/polaris/polaris-react/tests/utilities/breakpoints.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/within-filter-context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/within-content-context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/use-deep-effect.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/use-deep-compare-ref.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/use-deep-callback.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/components.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/banner-context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-previous.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-on-value-change.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-lazy-ref.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-is-mounted-ref.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-is-after-initial-mount.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-index-resource-state.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-event-listener.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-disable-interaction.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-component-did-mount.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-breakpoints.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/use-breakpoints-ssr.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/tests/is-input-focused.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/sticky-manager/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/sticky-manager/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/scroll-lock-manager/hooks.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/scroll-lock-manager/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/scroll-lock-manager/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/portals/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/portals/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/media-query/hooks.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/media-query/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/media-query/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/link/hooks.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/link/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/link/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/index-table/tests/hooks-useRowSelected.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/index-table/tests/hooks-useRowHovered.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/index-table/tests/hooks-useContainerScroll.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/index-provider/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/i18n/hooks.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/i18n/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/i18n/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/frame/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/focus-manager/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/focus-manager/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/features/hooks.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/features/tests/hooks.test.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/ephemeral-presence-manager/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/combobox/hooks.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/combobox/context.tsx',
    '/Users/foo/polaris/polaris-react/src/utilities/combobox/tests/hook.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/VideoThumbnail/VideoThumbnail.tsx',
    '/Users/foo/polaris/polaris-react/src/components/VideoThumbnail/VideoThumbnail.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/VideoThumbnail/tests/VideoThumbnail.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledLink/UnstyledLink.tsx',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledLink/tests/UnstyledLink.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledButton/utils.tsx',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledButton/UnstyledButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/UnstyledButton/tests/UnstyledButton.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Truncate/Truncate.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Truncate/tests/Truncate.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TrapFocus/TrapFocus.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TrapFocus/tests/TrapFocus.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/tests/TopBar.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/UserMenu/tests/UserMenu.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchField/SearchField.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchField/tests/SearchField.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchDismissOverlay/tests/SearchDismissOverlay.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Search/Search.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Search/tests/Search.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/Menu.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/tests/Menu.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/components/Message/Message.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TopBar/components/Menu/components/Message/tests/Message.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/tests/Tooltip.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tooltip/components/TooltipOverlay/tests/TooltipOverlay.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Toast/Toast.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Toast/Toast.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Toast/tests/Toast.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Thumbnail/Thumbnail.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Thumbnail/Thumbnail.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Thumbnail/tests/Thumbnail.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextField/tests/TextField.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Spinner/Spinner.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Spinner/tests/Spinner.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Resizer/Resizer.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextField/components/Resizer/tests/Resizer.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextContainer/TextContainer.tsx',
    '/Users/foo/polaris/polaris-react/src/components/TextContainer/TextContainer.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Text/Text.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Text/Text.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Text/tests/Text.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tag/Tag.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tag/Tag.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tag/tests/Tag.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/Tabs.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/Tabs.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/tests/Tabs.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/TabMeasurer/tests/TabMeasurer.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/Tab.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/tests/Tab.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/RenameModal/RenameModal.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/RenameModal/tests/RenameModal.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/DuplicateModal/DuplicateModal.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/components/DuplicateModal/tests/DuplicateModal.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Panel/Panel.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Panel/tests/Panel.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/List/List.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/List/tests/List.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/CreateViewModal/CreateViewModal.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Tabs/components/CreateViewModal/tests/CreateViewModal.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Sticky/Sticky.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Sticky/tests/Sticky.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Spinner/Spinner.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Spinner/Spinner.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Spinner/tests/Spinner.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonThumbnail/tests/SkeletonThumbnail.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonTabs/SkeletonTabs.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonTabs/SkeletonTabs.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonPage/SkeletonPage.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonPage/SkeletonPage.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonPage/tests/SkeletonPage.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonDisplayText/tests/SkeletonDisplayText.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SkeletonBodyText/tests/SkeletonBodyText.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Sheet/Sheet.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Sheet/Sheet.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Sheet/tests/Sheet.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ShadowBevel/ShadowBevel.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ShadowBevel/ShadowBevel.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ShadowBevel/tests/ShadowBevel.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SettingToggle/SettingToggle.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SettingToggle/SettingToggle.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SettingToggle/tests/SettingToggle.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SettingAction/SettingAction.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SelectAllActions/SelectAllActions.tsx',
    '/Users/foo/polaris/polaris-react/src/components/SelectAllActions/tests/SelectAllActions.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Select/Select.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Select/Select.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Select/tests/Select.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/Scrollable.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/Scrollable.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/tests/Scrollable.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/components/ScrollTo/ScrollTo.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Scrollable/components/ScrollTo/tests/ScrollTo.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ScrollLock/tests/ScrollLock.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ResourceList/ResourceList.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ResourceList/ResourceList.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ResourceList/tests/ResourceList.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ResourceItem/ResourceItem.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ResourceItem/ResourceItem.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ResourceItem/tests/ResourceItem.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/RangeSlider.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/RangeSlider.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/tests/RangeSlider.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/SingleThumb/tests/SingleThumb.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RadioButton/RadioButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RadioButton/RadioButton.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/RadioButton/tests/RadioButton.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ProgressBar/ProgressBar.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ProgressBar/ProgressBar.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ProgressBar/tests/ProgressBar.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PositionedOverlay/PositionedOverlay.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PortalsManager/PortalsManager.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PortalsManager/tests/PortalsManager.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PortalsManager/components/PortalsContainer/PortalsContainer.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Portal/Portal.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Portal/tests/Portal.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/tests/Popover.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Section/Section.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Section/tests/Section.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Pane/Pane.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Popover/components/Pane/tests/Pane.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PolarisTestProvider/tests/PolarisTestProvider.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Pagination/Pagination.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Pagination/Pagination.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Pagination/tests/Pagination.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PageActions/PageActions.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PageActions/PageActions.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/PageActions/tests/PageActions.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Page/Page.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Page/Page.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Page/tests/Page.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/Header.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/tests/Header.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/components/Title/Title.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/components/Title/tests/Title.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/OptionList.tsx',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/OptionList.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/tests/OptionList.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/components/Option/Option.tsx',
    '/Users/foo/polaris/polaris-react/src/components/OptionList/components/Option/tests/Option.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/context.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/Navigation.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/Navigation.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/tests/Navigation.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Section/Section.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Section/tests/Section.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/components/SecondaryNavigation/SecondaryNavigation.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Navigation/components/Item/components/SecondaryNavigation/tests/SecondaryNavigation.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/Modal.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/Modal.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/tests/Modal.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Section/Section.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Header/Header.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Footer/Footer.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Dialog/Dialog.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/Dialog/tests/Dialog.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Modal/components/CloseButton/CloseButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/MessageIndicator/MessageIndicator.tsx',
    '/Users/foo/polaris/polaris-react/src/components/MessageIndicator/tests/MessageIndicator.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/MediaQueryProvider/MediaQueryProvider.tsx',
    '/Users/foo/polaris/polaris-react/src/components/MediaQueryProvider/tests/MediaQueryProvider.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/MediaCard/MediaCard.tsx',
    '/Users/foo/polaris/polaris-react/src/components/MediaCard/MediaCard.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/MediaCard/tests/MediaCard.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Loading/Loading.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Loading/Loading.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Loading/tests/Loading.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/tests/Listbox.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/TextOption/TextOption.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/TextOption/tests/TextOption.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Section/Section.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Section/tests/Section.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Option/Option.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Option/tests/Option.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Loading/Loading.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Loading/tests/Loading.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Header/Header.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Header/tests/Header.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Action/Action.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Action/tests/Action.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/List/List.tsx',
    '/Users/foo/polaris/polaris-react/src/components/List/List.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/List/tests/List.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/List/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/List/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Link/Link.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Link/Link.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Link/tests/Link.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/LegacyTabs.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/LegacyTabs.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/tests/LegacyTabs.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/TabMeasurer/TabMeasurer.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/TabMeasurer/tests/TabMeasurer.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Tab/Tab.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Tab/tests/Tab.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Panel/Panel.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Panel/tests/Panel.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/List/List.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/List/tests/List.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/LegacyStack.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/LegacyStack.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/tests/LegacyStack.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyStack/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/LegacyFilters.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/LegacyFilters.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/tests/LegacyFilters.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/TagsWrapper/TagsWrapper.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/TagsWrapper/tests/TagsWrapper.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/LegacyCard.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/LegacyCard.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/tests/LegacyCard.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Subsection/Subsection.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Subsection/tests/Subsection.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Section/Section.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Section/tests/Section.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Header/Header.tsx',
    '/Users/foo/polaris/polaris-react/src/components/LegacyCard/components/Header/tests/Header.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Layout/Layout.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Layout/Layout.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Layout/tests/Layout.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Layout/components/Section/Section.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Labelled/Labelled.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Labelled/tests/Labelled.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Label/Label.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Label/tests/Label.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/KeypressListener/KeypressListener.tsx',
    '/Users/foo/polaris/polaris-react/src/components/KeypressListener/tests/KeypressListener.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/KeyboardKey/KeyboardKey.tsx',
    '/Users/foo/polaris/polaris-react/src/components/KeyboardKey/KeyboardKey.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/KeyboardKey/tests/KeyboardKey.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineStack/InlineStack.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineStack/InlineStack.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineStack/tests/InlineStack.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineGrid/InlineGrid.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineGrid/InlineGrid.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineGrid/tests/InlineGrid.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineError/InlineError.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineError/InlineError.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineError/tests/InlineError.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineCode/InlineCode.tsx',
    '/Users/foo/polaris/polaris-react/src/components/InlineCode/tests/InlineCode.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Indicator/Indicator.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Indicator/tests/Indicator.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/ScrollContainer/ScrollContainer.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/ScrollContainer/tests/ScrollContainer.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Row/Row.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Row/tests/Row.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Checkbox/Checkbox.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Checkbox/tests/Checkbox.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Cell/Cell.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexTable/components/Cell/tests/Cell.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexProvider/IndexProvider.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexProvider/tests/IndexProvider.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/IndexFilters.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/IndexFilters.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/tests/IndexFilters.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/hooks/useSetIndexFiltersMode/useSetIndexFiltersMode.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/hooks/useIsSticky/tests/useIsSticky.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/UpdateButtons/UpdateButtons.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/UpdateButtons/tests/UpdateButtons.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/SortButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/tests/SortButton.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/components/DirectionButton/DirectionButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SortButton/components/DirectionButton/tests/DirectionButton.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/EditColumnsButton/EditColumnsButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/IndexFilters/components/Container/Container.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Image/Image.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Image/tests/Image.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Icon/Icon.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Icon/Icon.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Icon/tests/Icon.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Grid/Grid.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Grid/Grid.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Grid/tests/Grid.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Grid/components/Cell/Cell.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Grid/components/Cell/tests/Cell.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FullscreenBar/FullscreenBar.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FullscreenBar/FullscreenBar.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FullscreenBar/tests/FullscreenBar.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/Frame.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/Frame.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/tests/Frame.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ToastManager/ToastManager.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ToastManager/tests/ToastManager.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Toast/Toast.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Toast/tests/Toast.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Loading/Loading.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/Loading/tests/Loading.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/DiscardConfirmationModal.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/tests/DiscardConfirmationModal.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Frame/components/CSSAnimation/CSSAnimation.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/FormLayout.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/FormLayout.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/tests/FormLayout.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Group/Group.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FormLayout/components/Group/tests/Group.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Form/Form.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Form/Form.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Form/tests/Form.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FooterHelp/FooterHelp.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FooterHelp/FooterHelp.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FooterHelp/tests/FooterHelp.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FocusManager/FocusManager.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FocusManager/tests/FocusManager.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Focus/Focus.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Focus/tests/Focus.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/Filters.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/Filters.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/tests/Filters.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/SearchField/SearchField.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/SearchField/tests/SearchField.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FiltersBar/FiltersBar.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FiltersBar/tests/FiltersBar.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Filters/components/FilterPill/tests/FilterPill.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/FilterActionsProvider/FilterActionsProvider.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ExceptionList/ExceptionList.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ExceptionList/ExceptionList.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ExceptionList/tests/ExceptionList.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EventListener/EventListener.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EventListener/tests/EventListener.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EphemeralPresenceManager/EphemeralPresenceManager.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EphemeralPresenceManager/tests/EphemeralPresenceManager.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EmptyState/EmptyState.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EmptyState/EmptyState.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EmptyState/tests/EmptyState.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EmptySearchResult/EmptySearchResult.tsx',
    '/Users/foo/polaris/polaris-react/src/components/EmptySearchResult/tests/EmptySearchResult.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/context.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/DropZone.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/DropZone.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/tests/DropZone.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/components/FileUpload/FileUpload.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Divider/Divider.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Divider/Divider.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Divider/tests/Divider.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DescriptionList/DescriptionList.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DescriptionList/DescriptionList.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DescriptionList/tests/DescriptionList.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/utilities.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/DatePicker.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/DatePicker.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/tests/DatePicker.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Weekday/Weekday.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Weekday/tests/Weekday.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Month/Month.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Month/tests/Month.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Day/Day.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Day/tests/Day.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/tests/DataTable.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Navigation/Navigation.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Navigation/tests/Navigation.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Cell/Cell.tsx',
    '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Cell/tests/Cell.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Connected/Connected.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Connected/tests/Connected.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Connected/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/Combobox.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/Combobox.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/tests/Combobox.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/components/TextField/TextField.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Combobox/components/TextField/tests/TextField.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/ColorPicker.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/ColorPicker.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/tests/ColorPicker.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/tests/ColorPicker-ssr.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/Slidable/Slidable.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/Slidable/tests/Slidable.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/HuePicker/HuePicker.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/HuePicker/tests/HuePicker.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/AlphaPicker/AlphaPicker.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ColorPicker/components/AlphaPicker/tests/AlphaPicker.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Collapsible/Collapsible.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Collapsible/Collapsible.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Collapsible/tests/Collapsible.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ChoiceList/ChoiceList.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ChoiceList/ChoiceList.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ChoiceList/tests/ChoiceList.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Choice/Choice.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Choice/tests/Choice.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Checkbox/Checkbox.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Checkbox/Checkbox.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Checkbox/tests/Checkbox.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/CheckableButton/CheckableButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/CheckableButton/tests/CheckableButton.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Card/Card.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Card/Card.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Card/tests/Card.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/CalloutCard/CalloutCard.tsx',
    '/Users/foo/polaris/polaris-react/src/components/CalloutCard/CalloutCard.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/CalloutCard/tests/CalloutCard.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/ButtonGroup.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/ButtonGroup.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/tests/ButtonGroup.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Button/utils.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Button/Button.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Button/Button.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Button/tests/utils.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Button/tests/Button.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/BulkActions.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/tests/BulkActions.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/hooks/tests/use-is-bulk-actions-sticky.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionMenu/index.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionMenu/BulkActionMenu.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionMenu/tests/BulkActionMenu.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Box/Box.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Box/Box.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Box/tests/Box.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BlockStack/BlockStack.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BlockStack/BlockStack.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/BlockStack/tests/BlockStack.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Bleed/Bleed.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Bleed/Bleed.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Bleed/tests/Bleed.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Banner/tests/Banner.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Badge/Badge.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Badge/Badge.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Badge/tests/Badge.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Badge/components/Pip/Pip.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Backdrop/Backdrop.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Backdrop/tests/Backdrop.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Avatar/Avatar.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Avatar/Avatar.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Avatar/tests/Avatar.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Avatar/tests/Avatar-ssr.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/Autocomplete.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/Autocomplete.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/tests/Autocomplete.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/components/MappedOption/MappedOption.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/components/MappedOption/tests/MappedOption.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/components/MappedAction/MappedAction.tsx',
    '/Users/foo/polaris/polaris-react/src/components/Autocomplete/components/MappedAction/tests/MappedAction.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AppProvider/AppProvider.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AppProvider/AppProvider.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AppProvider/tests/AppProvider.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AfterInitialMount/AfterInitialMount.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AfterInitialMount/test/AfterInitialMount.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/ActionMenu.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/tests/ActionMenu.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/RollupActions/tests/RollupActions.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/MenuGroup/tests/MenuGroup.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/Actions/Actions.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/Actions/tests/Actions.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/ActionList.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/ActionList.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/tests/ActionList.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Section/Section.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Section/tests/Section.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Item/Item.tsx',
    '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Item/tests/Item.test.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AccountConnection/AccountConnection.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AccountConnection/AccountConnection.stories.tsx',
    '/Users/foo/polaris/polaris-react/src/components/AccountConnection/tests/AccountConnection.test.tsx',
    '/Users/foo/polaris/polaris-react/playground/stories.tsx',
    '/Users/foo/polaris/polaris-react/playground/Playground.tsx',
    '/Users/foo/polaris/polaris-react/playground/KitchenSink.tsx',
    '/Users/foo/polaris/polaris-react/playground/DetailsPage.tsx',
  ],
  perfectResult: {
    // Duplicate component names. Would need parent layers/pages to differentiate
    '109103:28058' /* Spinner */:
      '/Users/foo/polaris/polaris-react/src/components/Spinner/Spinner.tsx',
    '108224:8280' /* Section */:
      '/Users/foo/polaris/polaris-react/src/components/ActionList/components/Section/Section.tsx',
    '111606:72844' /* Option */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Option/Option.tsx',
    '111636:2455' /* Cell */:
      '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Cell/Cell.tsx',
    '109785:19497' /* Search field */:
      '/Users/foo/polaris/polaris-react/src/components/TopBar/components/SearchField/SearchField.tsx',
    '108458:10011' /* Contextual save bar */:
      '/Users/foo/polaris/polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.tsx',
    '108407:11851' /* Text field */:
      '/Users/foo/polaris/polaris-react/src/components/TextField/TextField.tsx',
    '108368:1341' /* Checkbox */:
      '/Users/foo/polaris/polaris-react/src/components/Checkbox/Checkbox.tsx',

    // Duplicate component name in same layer
    '108797:54548' /* Day */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Day/Day.tsx',

    // Non-matching component names. Would need parent layers/pages identify
    '108943:4401' /* Title bar */:
      '/Users/foo/polaris/polaris-react/src/components/Modal/components/Header/Header.tsx',

    // Typo in component name / not an exact match
    '111674:1339' /* Lisbox */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/Listbox.tsx',
    '110912:43515' /* Index filter */:
      '/Users/foo/polaris/polaris-react/src/components/IndexFilters/IndexFilters.tsx',

    // simple matches
    '109630:31250' /* Video thumbnail */:
      '/Users/foo/polaris/polaris-react/src/components/VideoThumbnail/VideoThumbnail.tsx',
    '109785:19170' /* Top bar */:
      '/Users/foo/polaris/polaris-react/src/components/TopBar/TopBar.tsx',
    '109785:19481' /* User menu */:
      '/Users/foo/polaris/polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx',
    '110065:49636' /* Tooltip */:
      '/Users/foo/polaris/polaris-react/src/components/Tooltip/Tooltip.tsx',
    '108524:15659' /* Toast */: '/Users/foo/polaris/polaris-react/src/components/Toast/Toast.tsx',
    '109135:42783' /* Thumbnail */:
      '/Users/foo/polaris/polaris-react/src/components/Thumbnail/Thumbnail.tsx',
    '109012:41728' /* Tag */: '/Users/foo/polaris/polaris-react/src/components/Tag/Tag.tsx',
    '110386:1423' /* Tabs */: '/Users/foo/polaris/polaris-react/src/components/Tabs/Tabs.tsx',
    '110371:90046' /* Tab */:
      '/Users/foo/polaris/polaris-react/src/components/Tabs/components/Tab/Tab.tsx',
    '62007:21648' /* Skeleton thumbnail */:
      '/Users/foo/polaris/polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx',
    '62007:21531' /* Skeleton display text */:
      '/Users/foo/polaris/polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.tsx',
    '62007:21609' /* Skeleton body text */:
      '/Users/foo/polaris/polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.tsx',
    '108526:14477' /* Select */:
      '/Users/foo/polaris/polaris-react/src/components/Select/Select.tsx',
    '110491:47135' /* Resource list */:
      '/Users/foo/polaris/polaris-react/src/components/ResourceList/ResourceList.tsx',
    '53359:25889' /* .Resource Item */:
      '/Users/foo/polaris/polaris-react/src/components/ResourceItem/ResourceItem.tsx',
    '109643:22164' /* Range slider */:
      '/Users/foo/polaris/polaris-react/src/components/RangeSlider/RangeSlider.tsx',
    '108368:2270' /* Radio button */:
      '/Users/foo/polaris/polaris-react/src/components/RadioButton/RadioButton.tsx',
    '27579:4563' /* Progress bar */:
      '/Users/foo/polaris/polaris-react/src/components/ProgressBar/ProgressBar.tsx',
    '110421:9260' /* Popover */:
      '/Users/foo/polaris/polaris-react/src/components/Popover/Popover.tsx',
    '108807:10772' /* Pagination */:
      '/Users/foo/polaris/polaris-react/src/components/Pagination/Pagination.tsx',
    '108807:15671' /* Page actions */:
      '/Users/foo/polaris/polaris-react/src/components/PageActions/PageActions.tsx',
    '111691:69452' /* Page */: '/Users/foo/polaris/polaris-react/src/components/Page/Page.tsx',
    '111691:53161' /* Header */:
      '/Users/foo/polaris/polaris-react/src/components/Page/components/Header/Header.tsx',
    '109368:18066' /* Option list */:
      '/Users/foo/polaris/polaris-react/src/components/OptionList/OptionList.tsx',
    '109776:121231' /* Navigation */:
      '/Users/foo/polaris/polaris-react/src/components/Navigation/Navigation.tsx',
    '111368:23985' /* Modal */: '/Users/foo/polaris/polaris-react/src/components/Modal/Modal.tsx',
    '108974:9575' /* Footer */:
      '/Users/foo/polaris/polaris-react/src/components/Modal/components/Footer/Footer.tsx',
    '109745:85696' /* Media card */:
      '/Users/foo/polaris/polaris-react/src/components/MediaCard/MediaCard.tsx',
    '111674:30439' /* Header */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Header/Header.tsx',
    '111596:71602' /* Action */:
      '/Users/foo/polaris/polaris-react/src/components/Listbox/components/Action/Action.tsx',
    '108808:30098' /* Link */: '/Users/foo/polaris/polaris-react/src/components/Link/Link.tsx',
    '86562:46659' /* .Tabs legacy */:
      '/Users/foo/polaris/polaris-react/src/components/LegacyTabs/LegacyTabs.tsx',

    '78394:31942' /* .Layout */:
      '/Users/foo/polaris/polaris-react/src/components/Layout/Layout.tsx',
    '28210:12203' /* Inline error */:
      '/Users/foo/polaris/polaris-react/src/components/InlineError/InlineError.tsx',
    '109557:3763' /* Indicator */:
      '/Users/foo/polaris/polaris-react/src/components/Indicator/Indicator.tsx',
    '111680:45555' /* Index table */:
      '/Users/foo/polaris/polaris-react/src/components/IndexTable/IndexTable.tsx',
    '56963:30933' /* .Grid */: '/Users/foo/polaris/polaris-react/src/components/Grid/Grid.tsx',
    '110000:10540' /* Fullscreen bar */:
      '/Users/foo/polaris/polaris-react/src/components/FullscreenBar/FullscreenBar.tsx',
    '108808:30394' /* Footer help */:
      '/Users/foo/polaris/polaris-react/src/components/FooterHelp/FooterHelp.tsx',
    '111407:92131' /* Filters */:
      '/Users/foo/polaris/polaris-react/src/components/Filters/Filters.tsx',
    '111562:48065' /* Filters bar */:
      '/Users/foo/polaris/polaris-react/src/components/Filters/components/FiltersBar/FiltersBar.tsx',
    '111058:33366' /* Filter pill */:
      '/Users/foo/polaris/polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx',
    '108933:30513' /* Exception list */:
      '/Users/foo/polaris/polaris-react/src/components/ExceptionList/ExceptionList.tsx',
    '109979:8183' /* Empty state */:
      '/Users/foo/polaris/polaris-react/src/components/EmptyState/EmptyState.tsx',
    '109178:44479' /* Drop zone */:
      '/Users/foo/polaris/polaris-react/src/components/DropZone/DropZone.tsx',
    '109745:84282' /* Divider */:
      '/Users/foo/polaris/polaris-react/src/components/Divider/Divider.tsx',
    '109630:30271' /* Description list */:
      '/Users/foo/polaris/polaris-react/src/components/DescriptionList/DescriptionList.tsx',
    '108914:2585' /* DatePicker */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/DatePicker.tsx',
    '108797:52864' /* Day of week */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Weekday/Weekday.tsx',
    '108797:52863' /* Month */:
      '/Users/foo/polaris/polaris-react/src/components/DatePicker/components/Month/Month.tsx',
    '111636:2477' /* Data table */:
      '/Users/foo/polaris/polaris-react/src/components/DataTable/DataTable.tsx',
    '111683:62772' /* Navigation */:
      '/Users/foo/polaris/polaris-react/src/components/DataTable/components/Navigation/Navigation.tsx',
    '108433:7829' /* Color picker */:
      '/Users/foo/polaris/polaris-react/src/components/ColorPicker/ColorPicker.tsx',
    '109134:7785' /* Choice list */:
      '/Users/foo/polaris/polaris-react/src/components/ChoiceList/ChoiceList.tsx',
    '109372:20170' /* Card */: '/Users/foo/polaris/polaris-react/src/components/Card/Card.tsx',
    '109313:7455' /* Callout card */:
      '/Users/foo/polaris/polaris-react/src/components/CalloutCard/CalloutCard.tsx',
    '108782:4042' /* ButtonGroup */:
      '/Users/foo/polaris/polaris-react/src/components/ButtonGroup/Button group.tsx',
    '108641:35692' /* Button */:
      '/Users/foo/polaris/polaris-react/src/components/Button/Button.tsx',
    '110641:64122' /* Bulk actions */:
      '/Users/foo/polaris/polaris-react/src/components/BulkActions/BulkActions.tsx',
    '109293:4284' /* Banner */: '/Users/foo/polaris/polaris-react/src/components/Banner/Banner.tsx',
    '108227:921' /* Badge */: '/Users/foo/polaris/polaris-react/src/components/Badge/Badge.tsx',
    '107957:44068' /* Avatar */:
      '/Users/foo/polaris/polaris-react/src/components/Avatar/Avatar.tsx',
    '110065:29772' /* Secondary action */:
      '/Users/foo/polaris/polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx',
    '108977:15501' /* Action List */:
      '/Users/foo/polaris/polaris-react/src/components/ActionList/ActionList.tsx',
    '109630:23132' /* Account Connection */:
      '/Users/foo/polaris/polaris-react/src/components/AccountConnection/AccountConnection.tsx',
  },
}

export default polarisReact
