import { createReactCodeConnect } from '../create'
const fs = require('fs')
import prettier from 'prettier'

jest.mock('fs')

describe('createReactCodeConnect', () => {
  it('Should generate a boolean variant if the variant options are all boolean', async () => {
    fs.existsSync.mockReturnValue(false)

    await createReactCodeConnect({
      destinationDir: 'test',
      destinationFile: 'test.figma.tsx',
      config: { parser: 'react' },
      mode: 'CREATE',
      component: {
        id: '1:1',
        figmaNodeUrl: 'fake-url',
        name: 'Test',
        normalizedName: 'Test',
        type: 'COMPONENT_SET',
        componentPropertyDefinitions: {
          BooleanVariant: {
            type: 'VARIANT',
            defaultValue: 'true',
            variantOptions: ['true', 'false'],
          },
          BooleanVariant2: {
            type: 'VARIANT',
            defaultValue: 'True',
            variantOptions: ['True', 'False'],
          },
          BooleanVariant3: { type: 'VARIANT', defaultValue: 'yes', variantOptions: ['yes', 'no'] },
          BooleanVariant4: { type: 'VARIANT', defaultValue: 'Yes', variantOptions: ['Yes', 'No'] },
          BooleanVariant5: { type: 'VARIANT', defaultValue: 'on', variantOptions: ['on', 'off'] },
          BooleanVariant6: { type: 'VARIANT', defaultValue: 'On', variantOptions: ['On', 'Off'] },
          Variant: {
            type: 'VARIANT',
            defaultValue: 'Yes',
            variantOptions: ['Yes', 'No', 'Intermediate'],
          },
          Variant2: {
            type: 'VARIANT',
            defaultValue: 'Yes',
            variantOptions: ['True', 'SomethingElse'],
          },
        },
      },
    })

    const expected = await prettier.format(
      `\
import React from "react"
import { Test } from "./Test"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by \`figma connect create\` --
 * \`props\` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the \`example\` function to return the
 * code example you'd like to see in Figma
*/

figma.connect(Test, "fake-url", {
  props: {
    booleanVariant: figma.boolean("BooleanVariant"),
    booleanVariant2: figma.boolean("BooleanVariant2"),
    booleanVariant3: figma.boolean("BooleanVariant3"),
    booleanVariant4: figma.boolean("BooleanVariant4"),
    booleanVariant5: figma.boolean("BooleanVariant5"),
    booleanVariant6: figma.boolean("BooleanVariant6"),
    variant: figma.enum("Variant", {
      Yes: "yes",
      No: "no",
      Intermediate: "intermediate",
    }),
    variant2: figma.enum("Variant2", {
      True: "true",
      SomethingElse: "somethingelse",
    }),
  },
  example: (props) => <Test />,
})`,
      {
        parser: 'typescript',
        semi: false,
        trailingComma: 'all',
      },
    )

    expect(fs.writeFileSync).toHaveBeenCalledWith('test.figma.tsx', expected)
  })
})
