import React from 'react'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  'https://figma.com/design/test?node-id=1:1',
  {
    props: {
      label: figma.string('Label'),
      disabled: figma.boolean('Disabled'),
    },
    example: ({ label, disabled }) => (
      <Button disabled={disabled}>{label}</Button>
    ),
  },
)
