/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.figma.code.connect

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * Unit test for verify code connect plugin creates tasks.
 */
class FigmaCodeConnectPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.figma.code.connect")

        // Verify the result
        assertNotNull(project.tasks.findByName("parseCodeConnect"))
        assertNotNull(project.tasks.findByName("createCodeConnect"))
    }
}
