/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.6/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    kotlin("jvm")

    // Apply the maven-publish plugin to add support for publishing to Maven repositories.
    `maven-publish`

    // Apply the ktlint plugin to enforce code style.
    id("org.jlleitschuh.gradle.ktlint") version "12.1.1"

    // Json serialization plugin.
    kotlin("plugin.serialization") version "2.2.21"

    // Publishing plugin
    id("com.gradle.plugin-publish") version "1.2.1"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

repositories {
    mavenCentral()
}

// `kotlin-compiler-embeddable` is only used by the parser worker, which runs in an isolated JVM
// (see ParseCodeConnectWorkAction / ParseCodeConnectTask). It must NOT appear as a runtime dep of
// the plugin: putting it on the consumer's buildscript classpath causes IncompatibleClassChangeError
// against the Kotlin Gradle Plugin when versions diverge (notably Kotlin 2.3+).
//
// `compileOnly` lets us compile the worker action's PSI references; at runtime the consumer's
// `figmaCodeConnectParser` configuration (declared in FigmaCodeConnectPlugin.apply) resolves the
// compiler jars and Gradle's worker API loads them only into the forked worker process.
val parserClasspath: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    // WARNING!!! Adding dependencies to the plugins in highly discouraged. Make sure you know
    // what you are doing before adding dependencies to the plugin.

    compileOnly(libs.kotlin.compiler.embeddable)
    parserClasspath(libs.kotlin.compiler.embeddable)

    implementation(libs.kotlin.serialization)
    implementation(libs.kotlin.poet)
    implementation(project(":annotations"))

    // Testing dependencies
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation(libs.kotlin.compiler.embeddable)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation(project(":plugin"))
}

gradlePlugin {
    // Define the plugin
    val figmaCodeConnect by plugins.creating {
        id = property("ID").toString()
        implementationClass = property("IMPLEMENTATION_CLASS").toString()
        group = property("GROUP").toString()

        version = property("VERSION").toString()
        displayName = property("DISPLAY_NAME").toString()
        description = property("DESCRIPTION").toString()
        tags = listOf("kotlin", "figma", "compose", "android")
    }

    website.set(property("WEBSITE").toString())
    vcsUrl.set(property("VCS_URL").toString())
}

// Add a source set for the functional test suite
val functionalTestSourceSet =
    sourceSets.create("functionalTest") {
    }

configurations["functionalTestImplementation"].extendsFrom(configurations["testImplementation"])
configurations["functionalTestRuntimeOnly"].extendsFrom(configurations["testRuntimeOnly"])

// Add a task to run the functional tests
val functionalTest by tasks.registering(Test::class) {
    testClassesDirs = functionalTestSourceSet.output.classesDirs
    classpath = functionalTestSourceSet.runtimeClasspath
    useJUnitPlatform()
}

gradlePlugin.testSourceSets.add(functionalTestSourceSet)

// TestKit isolates the plugin under test on a custom classpath. The worker process spawned by
// ParseCodeConnectTask still needs kotlin-compiler-embeddable; in production it comes from the
// `figmaCodeConnectParser` configuration resolved in the consumer's project. For TestKit, the
// test build file declares `repositories { mavenCentral() }` so the same resolution path works.
// We don't need to add anything to pluginUnderTestMetadata for the worker classpath itself —
// the worker classpath is resolved per-task at execution time.

tasks.named<Task>("check") {
    // Run the functional tests as part of `check`
    dependsOn(functionalTest)
}

tasks.named<Test>("test") {
    // Use JUnit Jupiter for unit tests.
    useJUnitPlatform()
}
